### PR TITLE
[Generator] Replace -iquote by -isystem for frameworks in xcconfig

### LINKED ISSUE #5589: inhibit_all_warnings doesn't work for header files
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?
- Enabled lots of warnings
- Enabled "treat warnings as errors" on target
- Added Couchbase Lite pod
- Added `inhibit_all_warnings!` to Podfile
- `pod install`
- Tried to compile workspace
## What did you expect to happen?

Expected the project to compile without issues.
## What happened instead?

The headers that are included when doing `#import <CouchBaseLite/...>` generate a few warnings (handled as errors), which stops the project from compiling.
## 

This isn't an issue with CBL, but with the fact that even when I explicitly ask Cocoapods to inhibit warnings for a pod (or all of them), their headers can still be a source for warnings.

What I ended up doing was specifying `--system-header-prefix=CouchbaseLite` as part of _OTHER_CFLAGS_ - mentioned in http://clang.llvm.org/docs/UsersManual.html#controlling-diagnostics-in-system-headers - maybe this could be an option for other pods as well.

### PR DESCRIPTION
**Pull request by guillaumealgis**
🌈

- Replace usage of the `-iquote` compiler flag by `-isystem` when searching for framework headers. This will silence compilation warning in the Pods' headers files.
> "Header files found in directories added to the search path with the `-isystem` and `-idirafter` command-line options are treated as system headers for the purposes of diagnostics"
> "All warnings [...] are suppressed while GCC is processing a system header"
[https://gcc.gnu.org/onlinedocs/cpp/System-Headers.html](https://gcc.gnu.org/onlinedocs/cpp/System-Headers.html)

- Update unit tests to reflect the above change.

Integrations tests are updated in https://github.com/CocoaPods/cocoapods-integration-specs/pull/94.

This fixes #5589.

When I tested locally with `bundle exec rake spec:all`, it failed on the Alamofire example, but I *think* this is normal and the example was not updated for Xcode 8 (please correct me if I'm wrong). When running the same tests as Travis thought, everything passed.

```
bundle exec bacon spec/functional/command/cache/clean_spec.rb spec/unit/installer/pod_source_installer_spec.rb spec/unit/installer/xcode/pods_project_generator/target_installer_spec.rb spec/unit/target/pod_target_spec.rb spec/unit/validator_spec.rb spec/unit/installer/analyzer/pod_variant_set_spec.rb spec/unit/installer/xcode/pods_project_generator_spec.rb spec/unit/installer/pre_install_hooks_context_spec.rb spec/functional/command/ipc/list_spec.rb spec/unit/downloader/cache_spec.rb spec/functional/command/init_spec.rb spec/functional/command/spec_spec.rb spec/functional/command/install_spec.rb spec/functional/command_spec.rb spec/unit/sandbox/pod_dir_cleaner_spec.rb spec/unit/hooks_manager_spec.rb spec/unit/generator/module_map_spec.rb spec/unit/external_sources/abstract_external_source_spec.rb spec/functional/command/ipc/spec_spec.rb spec/unit/generator/header_spec.rb spec/unit/generator/acknowledgements/markdown_spec.rb spec/unit/external_sources/downloader_source_spec.rb spec/unit/installer/post_install_hooks_context_spec.rb spec/unit/installer/user_project_integrator/target_integrator/xcconfig_integrator_spec.rb spec/functional/command/repo/update_spec.rb spec/unit/generator/info_plist_file_spec.rb spec/unit/user_interface/inspector_reporter_spec.rb spec/unit/user_interface_spec.rb spec/unit/generator/dummy_source_spec.rb spec/unit/sandbox_spec.rb spec/functional/command/lib/create_spec.rb spec/unit/external_sources/path_source_spec.rb spec/functional/command/lib/list_spec.rb spec/unit/sandbox/file_accessor_spec.rb spec/unit/config_spec.rb spec/unit/user_interface/error_report_spec.rb spec/unit/generator/prefix_header_spec.rb spec/unit/installer_spec.rb spec/functional/user_interface_spec.rb spec/unit/sandbox/podspec_finder_spec.rb spec/unit/command_spec.rb spec/unit/installer/xcode/pods_project_generator/file_references_installer_spec.rb spec/functional/command/repo/push_spec.rb spec/functional/command/repo_spec.rb spec/unit/executable_spec.rb spec/unit/generator/embed_frameworks_script_spec.rb spec/unit/external_sources/podspec_source_spec.rb spec/unit/installer/analyzer/target_inspector_spec.rb spec/functional/command/repo/lint_spec.rb spec/functional/command/outdated_spec.rb spec/unit/generator/acknowledgements_spec.rb spec/functional/command/setup_spec.rb spec/unit/installer/podfile_validator_spec.rb spec/functional/command/cache/list_spec.rb spec/functional/command/update_spec.rb spec/unit/generator/xcconfig/pod_xcconfig_spec.rb spec/functional/command/ipc/update_search_index_spec.rb spec/unit/downloader_spec.rb spec/unit/installer/installation_options_spec.rb spec/functional/command/list_spec.rb spec/unit/installer/analyzer/pod_variant_spec.rb spec/unit/installer/user_project_integrator_spec.rb spec/unit/generator/copy_resources_script_spec.rb spec/unit/target_spec.rb spec/unit/project_spec.rb spec/unit/installer/source_provider_hooks_context_spec.rb spec/unit/downloader/request_spec.rb spec/unit/installer/xcode/pods_project_generator/aggregate_target_installer_spec.rb spec/unit/installer/analyzer/sandbox_analyzer_spec.rb spec/functional/command/repo/list_spec.rb spec/unit/target/aggregate_target_spec.rb spec/unit/installer/analyzer_spec.rb spec/unit/installer/user_project_integrator/target_integrator_spec.rb spec/functional/command/repo/remove_spec.rb spec/functional/command/repo/add_spec.rb spec/unit/sandbox/headers_store_spec.rb spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb spec/unit/sources_manager_spec.rb spec/unit/generator/xcconfig_spec.rb spec/unit/resolver_spec.rb spec/unit/generator/xcconfig/aggregate_xcconfig_spec.rb spec/unit/external_sources_spec.rb spec/unit/generator/bridge_support_spec.rb spec/functional/command/ipc/repl_spec.rb spec/unit/generator/acknowledgements/plist_spec.rb spec/unit/sandbox/path_list_spec.rb spec/functional/command/ipc/podfile_spec.rb spec/unit/generator/xcconfig/xcconfig_helper_spec.rb spec/unit/library_spec.rb
```

This is my first PR to CocoaPods, please let me know if I missed anything 👍

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! 
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* [Generator] Replace -iquote by -isystem for frameworks in xcconfig 
  [guillaumealgis](https://github.com/guillaumealgis)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by benasher44** [comment]
Thanks for the PR! The main issue here is that I think this will render `inhibit_all_warnings` useless (i.e. it's as if it's always on) for headers files, since it appears you're always using `-isystem`, instead of of conditionally using it when `inhibit_all_warnings` is set. Maybe we should only use `-isystem` when `inhibit_all_warnings` is used?

**Comment by DanToml** [comment]
@benasher44 I'd +1 the only using `-isystem` when `inihibit_all_warnings` is used. I actually thought we already did this though 🤔.

**Comment by benasher44** [comment]
I'm not sure if it changed, but based on the code changed here, it seems to currently be unconditional.

**Comment by guillaumealgis** [comment]
Thanks for the feedback @benasher44 and @DanToml, I completely agree we should only use `-isystem` when `inhibit_all_warnings` is set 👍🏻
I'll try to fix that this week.

Regarding the failing tests, is there a way to have this branch tested using the fixed integrations tests in https://github.com/CocoaPods/cocoapods-integration-specs/pull/94 ?

And yes, it is currently unconditionally set to use `-iquote` for frameworks. I have seen warnings in my Pods headers ever since I added `use_frameworks!` to my Podfile.

**Comment by benasher44** [comment]
@guillaumealgis awesome! Yep, you can update the .gitmodules file on your branch to point to your fork, and then you should be able to get travis to run using the change you made. That said, I'm not to worried about that yet. I'm more interested in seeing the `inhibit_all_warnings` fix. After that your integration specs branch may be much different anyway.

**Comment by benasher44** [comment]
Hi @guillaumealgis! We'd love to see this ship! Anything we can do?

**Comment by guillaumealgis** [comment]
Sorry for the lack of response on this @benasher44.

I started working on using `inhibit_all_warnings` to determine which include flag to use, but I'm stuck on an issue I'm hopping you'll be able to help with.

The main problem is that I wasn't aware that you could set the `inhibit_warnings` flag on a per pod_target basis.
This is a problem because we are generating the content of `OTHER_CFLAGS` with the include flags at the aggregate_target level, not the pod_target level. So right now, all pod_targets share the same include flag.

I managed to "fix" the issue when generating the content of `OTHER_CFLAGS` for framework-based pods, by looking  at each pod_target (see https://github.com/CocoaPods/CocoaPods/pull/6401/commits/f1c461b8cb20abd54bbc5e3c4836e44ec730a64b).
But when adding the include flags for non-buildable framework targets (not quite sure what those are btw) or library-based pods, only one directory is included, so we cannot have different flags (`-isystem` or `-iquote`) for each target 😔

Hope I'm clear and you'll be able to help, thanks a lot!

**Comment by benasher44** [comment]
I believe for pod-level includes, you'll want to look at the `pod_xcconfig.rb` in the same folder there. I believe this is why we had the `XCConfigHelper`, which allowed all these generators to share the logic for generating these. Does that make sense?

**Comment by benasher44** [comment]
@guillaumealgis does that make sense? Anything else we can do to help this along? Cheers!

**Comment by guillaumealgis** [comment]
Hi @benasher44, sorry yeah I think it makes sense, I just need to find some time to look into this 😔

**Comment by benasher44** [comment]
No worries!

**Comment by adellibovi** [comment]
Wow, this would definitely be super cool to have 👍

**Comment by benasher44** [comment]
@guillaumealgis if you're feeling spread thin, there might be some folks who'd be willing to push this PR across the finish line. Would that be alright?

**Comment by guillaumealgis** [comment]
Sure, absolutely!

**Comment by guillaumealgis** [comment]
Just to keep you posted, I worked for a few hours tonight on this and made some *relative* progress.

This is much harder than anticipated (for me at least) because all the headers are added to the xcconfig files in one pass (with the `sandbox.public_headers` thingy if I'm not mistaken), instead of per target. So this implies some non-trivial changes to how the headers are handled.

I'm considering removing all uses of `HEADER_SEARCH_PATHS` everywhere, because [according to Samantha Marshall](https://pewpewthespells.com/blog/buildsettings.html#header_search_paths) this is the same as GCC's `-I`, which is the same as `-isystem`. So instead of defining the search paths multiples times with uncertain results regarding warnings silencing, I'd say we'd be better off just adding `-isystem` and `-iquote` to `OTHER_CFLAGS` where needed.

I'm going to try and work a bit more on it this week, no promises :)

**Comment by benasher44** [comment]
@guillaumealgis thanks for the update! We're rooting for ya!

**Comment by guillaumealgis** [comment]
So. I think I kinda got something working. Haven't fixed the test suite yet, but I'm feeling pretty confident given the few tests I did locally.

The gist of it is : use `-I` for all headers, and add a `-isystem` include flag for the silenced Pods' headers.
This allow all syntaxes for importing (`#import "..."`, `#import <...>`, `@import` etc.) and silence the warnings per-Pod (as per https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html).

I'll take a look at the tests soon™.

**Comment by adellibovi** [comment]
I don't know for which reason but with the latest version 1.3.0 this doesn't seem to happen.

**Comment by adellibovi** [comment]
Can we do anything to help this PR? :)

**Comment by guillaumealgis** [comment]
I'm still looking to complete this (as I currently have ~20 warnings from dependencies in my project), but can't find the time and motivation to do so 😣

The remaining work should be iirc :

- Rebase on master to integrate the latest Cocoapods changes
- Add tests for the new behavior / fix the non-passing tests

**Comment by guillaumealgis** [comment]
Made some progress today.

- The unit tests are now fixed and passing
- The integration tests are updated (see https://github.com/CocoaPods/cocoapods-integration-specs/pull/94), but some are failing, caused what I believe to be a bug in Xcodeproj (https://github.com/CocoaPods/Xcodeproj/issues/509)

I'll wait for a response to https://github.com/CocoaPods/Xcodeproj/issues/509, and then we should be good to go for a review of the PR 🎉

**Comment by zhihuilong** [comment]
Keep watching, and hope the PR can be merged. The warnings generated by pods are very annoyed😡.

**Comment by guillaumealgis** [comment]
Wooo all green :)
Not sure if that's the right way to point to the integration specs though.

Please let me know if I need to change anything! Thanks!

**Comment by guillaumealgis** [comment]
Yeah. So maybe I should have tested more... It does not always work 😭

I'll fix and let you know...

**Comment by guillaumealgis** [comment]
Ok fixed. The problem was that for frameworks, we can use two syntaxes to include the headers :

```
#import "Framework/Framework.h"
```

or just

```
#import "Framework.h"
```

This former is possible because we are using the `-F` (or `FRAMEWORK_SEARCH_PATHS`, which is the same) flag to include the framework path in the header search paths, the latter because of `-I` (or `HEADER_SEARCH_PATHS`).

So only just adding `-isystem` to silence the warnings was working when the header was included using `#import "Framework.h"` (because `-isystem` if the counterpart of `-I` for system headers), but if the header is included using `#import "Framework/Framework.h"`, the path was resolved by the `-F` flag, and thus not silenced.

So now we add a [`-iframework`](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-iframework) counterpart for each `-F` entry, which will act the same way as `-isystem` does.

**Comment by guillaumealgis** [comment]
Hi @benasher44, what are the next step to get this merged? Thanks!

**Comment by dnkoutso** [comment]
@guillaumealgis please first rebase. Then we will see if that can make it 1.4.0

**Comment by guillaumealgis** [comment]
@dnkoutso here you go :)

**Comment by natanrolnik** [comment]
Hope this one makes it to 1.4.0. Thanks for the PR, @guillaumealgis

**Comment by nikolaykasyanov** [comment]
In my opinion, this looks like a must for 1.4.0 release. Let me explain why. 1.4.0 bumps xcodeproj gem, whose latest version enables new Xcode warnings for CP targets, thus causing warnings (and even errors if "treat warnings as errors" is enabled).

Example: Masonry pod (1.0.2) causes build errors (we use "treat warnings as errors") with CocoaPods 1.4.0 because of missing `void` in argumentless block definitions.

**Comment by adellibovi** [comment]
How could we move this forward? :)

**Comment by dnkoutso** [comment]
@guillaumealgis I wanted to apologize for having this linger for so long. The problem has been for us to understand any potential implications of this change, if any.

I'd like to try your change eventually in our project (which is huge) and ensure that it continues to work.

Definitely on my radar and not deliberately ignoring it.

**Comment by dnkoutso** [comment]
P.S as I just saw this needs a rebase again :|

**Comment by guillaumealgis** [comment]
No problem @dnkoutso, glad to see we're able to push this forward 👍 

I started rebasing last Friday but due to the changes on the way Cocoapods now handles include search paths, this is a bit more work than last time. I'll try to fix the integrations tests asap.

**Comment by guillaumealgis** [comment]
Here you go @dnkoutso, should be good now.

Note that :
- 968877a should be removed before merging
- the changes in the integration specs are done on top of the branch `seg-fix-storing-headers` (because I needed these fixes too) https://github.com/CocoaPods/cocoapods-integration-specs/tree/seg-fix-storing-headers


I tested the changes on our (closed-source) project's moderately complex Podfile, and everything worked fine :

<details>
<summary>Podfile</summary>

    source 'https://github.com/CocoaPods/Specs.git'

    platform :ios, '10.0'
    use_frameworks!
    inhibit_all_warnings!

    target 'Foo' do
        libextobjc_version = '0.4.1'
        pod 'libextobjc/EXTKeyPathCoding', libextobjc_version
        pod 'libextobjc/EXTScope', libextobjc_version

        pod 'PSPDFKit', podspec:'https://customers.pspdfkit.com/cocoapods/<REDACTED>/pspdfkit/6.9.2.podspec'

        pod 'Crashlytics', '3.8.4'
        pod 'DejalActivityView', '1.2'
        pod 'Fabric', '1.6.11'
        pod 'GDIIndexBar', '0.3.5'
        pod 'handlebars-objc', '1.4.4'
        pod 'iCarousel', '1.8.3'
        pod 'JDStatusBarNotification', '1.5.5'
        pod 'JRSwizzle', '1.0'
        pod 'Masonry', '1.0.2'
        pod 'MBProgressHUD', '1.0.0'
        pod 'MMDrawerController', '0.6.0'
        pod 'MPColorTools', '1.6.1'
        pod 'NJKWebViewProgress', '0.2.3'
        pod 'Ono', '1.2.2'
        pod 'OrderedDictionary', '1.4'
        pod 'PBWebViewController', '0.4'
        pod 'Reachability', '3.2'
        pod 'Shimmer', '1.0.2'
        pod 'UIView+Shake', '1.3.0'

        pod 'Reveal-SDK', :configurations => ['Debug']

        pod 'NSAttributedStringMarkdownParser', :git => 'https://github.com/ipsosante/markdown.git', :branch => 'master'
        pod 'TOCropViewController', :git => 'https://github.com/ipsosante/TOCropViewController.git', :branch => 'master'
        pod 'MCPanelViewController', :git => 'https://github.com/ipsosante/MCPanelViewController.git', :branch => 'master'
    end
</details>

**Comment by segiddins** [comment]
Looking at the change in the integration specs, it seems a lot of the `-isystem` flags have been removed?

**Comment by guillaumealgis** [comment]
@segiddins Yes, because as far as I know, these add nothing if you already use `HEADER_SEARCH_PATHS`. All they do is silence warnings in the headers, which you don't want unless you use `inhibit_warning` (and it's not the case in the integration specs).

The gist of it is :
- Always use `HEADER_SEARCH_PATHS` and `FRAMEWORK_SEARCH_PATHS` to include headers for all pods
- Add the `-isystem` and `-iframework` flags to the `OTHER_CFLAGS` variable for each included path silenced by the `inhibit_warning` Podfile flag.

**Comment by segiddins** [comment]
> Xcode's UI might report an error, but the build succeeds and the error disappears. Because Xcode.

That's... not ideal

**Comment by guillaumealgis** [comment]
> That's... not ideal

Agreed. It happened pretty consistently each time after cleaning the project (the error would pop up on the line importing a Pod).
After removing my `DerivedData` folder I could not reproduce anymore, not matter what Podfile configuration I was using. I think this was a remaining artefact of the builds I did while working on the fix.

meh

**Comment by nikolaykasyanov** [comment]
I've just tried this branch on a relatively big project and got a crash.

```
NoMethodError - undefined method `build_pod_as_module?' for #<Pod::Podfile::TargetDefinition label=Pods-TicketWidget>
/Users/username/.rvm/gems/ruby-2.3.1/bundler/gems/CocoaPods-0bb6059ec1ae/lib/cocoapods/target/pod_target.rb:207:in `block in defines_module?'
/Users/username/.rvm/gems/ruby-2.3.1/bundler/gems/CocoaPods-0bb6059ec1ae/lib/cocoapods/target/pod_target.rb:207:in `any?'
/Users/username/.rvm/gems/ruby-2.3.1/bundler/gems/CocoaPods-0bb6059ec1ae/lib/cocoapods/target/pod_target.rb:207:in `defines_module?'
/Users/username/.rvm/gems/ruby-2.3.1/bundler/gems/CocoaPods-0bb6059ec1ae/lib/cocoapods/installer/xcode/pods_project_generator.rb:169:in `block (2 levels) in install_libraries'
/Users/username/.rvm/gems/ruby-2.3.1/bundler/gems/CocoaPods-0bb6059ec1ae/lib/cocoapods/installer/xcode/pods_project_generator.rb:168:in `map'
/Users/username/.rvm/gems/ruby-2.3.1/bundler/gems/CocoaPods-0bb6059ec1ae/lib/cocoapods/installer/xcode/pods_project_generator.rb:168:in `block in install_libraries'
/Users/username/.rvm/gems/ruby-2.3.1/bundler/gems/CocoaPods-0bb6059ec1ae/lib/cocoapods/user_interface.rb:142:in `message'
/Users/username/.rvm/gems/ruby-2.3.1/bundler/gems/CocoaPods-0bb6059ec1ae/lib/cocoapods/installer/xcode/pods_project_generator.rb:167:in `install_libraries'
/Users/username/.rvm/gems/ruby-2.3.1/bundler/gems/CocoaPods-0bb6059ec1ae/lib/cocoapods/installer/xcode/pods_project_generator.rb:65:in `generate!'
/Users/username/.rvm/gems/ruby-2.3.1/bundler/gems/CocoaPods-0bb6059ec1ae/lib/cocoapods/installer.rb:184:in `block in generate_pods_project'
/Users/username/.rvm/gems/ruby-2.3.1/bundler/gems/CocoaPods-0bb6059ec1ae/lib/cocoapods/user_interface.rb:64:in `section'
/Users/username/.rvm/gems/ruby-2.3.1/bundler/gems/CocoaPods-0bb6059ec1ae/lib/cocoapods/installer.rb:183:in `generate_pods_project'
/Users/username/.rvm/gems/ruby-2.3.1/bundler/gems/CocoaPods-0bb6059ec1ae/lib/cocoapods/installer.rb:119:in `install!'
/Users/username/.rvm/gems/ruby-2.3.1/bundler/gems/CocoaPods-0bb6059ec1ae/lib/cocoapods/command/install.rb:41:in `run'
/Users/username/.rvm/gems/ruby-2.3.1/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/username/.rvm/gems/ruby-2.3.1/bundler/gems/CocoaPods-0bb6059ec1ae/lib/cocoapods/command.rb:52:in `run'
/Users/username/.rvm/gems/ruby-2.3.1/bundler/gems/CocoaPods-0bb6059ec1ae/bin/pod:55:in `<top (required)>'
/Users/username/.rvm/gems/ruby-2.3.1/bin/pod:23:in `load'
/Users/username/.rvm/gems/ruby-2.3.1/bin/pod:23:in `<main>'
/Users/username/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/username/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

TicketWidget is a today extension target and defined in Podfile as following:

```ruby
platform :ios, '9.3'
inhibit_all_warnings!

...

target 'TicketWidget' do
    pod 'HockeySDK/CrashOnlyExtensionsLib', '~> 5.1', '>= 5.1.2'
    pod '3 internal development pods in a row', :path => 'whatever', :inhibit_warnings => false
    pod 'Masonry', '~> 1.0.2'
end
```

I can't share the whole Podfile, unfortunately, so please let me know if you need any further details.

**Comment by guillaumealgis** [comment]
Hi @nikolaykasyanov ,

I don't think it's related to the changes I made, I didn't touch anything related to what I can see in your stack trace. The `build_pod_as_module?` method is supposed to be defined in the cocoapods-core lib if I'm not mistaken.

Could you test if you can reproduce on `master` please ?

**Comment by genadyo** [comment]
@nikolaykasyanov I just had the same issue, make sure to update cocoapods-core to master too.

**Comment by nikolaykasyanov** [comment]
@guillaumealgis @genadyo thanks for your messages, it seems like cocoapods-core version was the culprit.

File: lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb [hunk 1]
```diff
@@ -137,32 +137,54 @@ def embedded_content_settings
...
+          header_search_paths.uniq!
+          silenced_header_search_paths.uniq!
+
+          build_settings = {
+            # Make headers discoverable with any syntax (quotes, brackets,
+            # @import, etc.)
+            'HEADER_SEARCH_PATHS' => XCConfigHelper.quote(header_search_paths),
+          }
+
+          # Use -isystem and -iframework for headers we want to treat as
```
Comment (segiddins) [inline lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb]: what is `-iframework` for? it doesnt seem to show up in the integration specs

Comment (guillaumealgis) [reply lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb]: `-iframework` is used in the same way `-isystem` is.

Note that despite the name, `-iframework` has noting to do with `-framework`:
From https://gcc.gnu.org/onlinedocs/gcc/Darwin-Options.html :

> **-iframework _dir_**
> Like -F except the directory is a treated as a system directory. The main difference between this -iframework and -F is that with -iframework the compiler does not warn about constructs contained within header files found via dir.

(`-F` being an equivalent of `FRAMEWORK_SEARCH_PATHS`)

The behavior I implemented in this PR is as follow :

- We use `HEADER_SEARCH_PATHS` to search for "regular" headers and `FRAMEWORK_SEARCH_PATHS` to find framework headers (as before)
- We only add the headers / framework path in `OTHER_C_FLAGS` using the `-isystem` or `-iframework` flags if the pod's warnings are silenced.

I should probably add some integration tests for all that. I'll try to do this asap but I don't have much time to work on this at the moment.

-------------------

Sidenote: I saw you added some comment to make `#import <...>` the only valid option in CocoaPods 2.0. I think it'll be difficult to get this behavior without silencing the headers (because that's how `-isystem` works). You'll end up in the invert situation of the one we're in today : pods without silenced warning won't report those warnings in header files (but I may be mistaken, I'm no expert in compiler flags 🙃 ).

**Comment by faken** [comment]
+1

File: lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb (hunk 1 above)
Comment (segiddins) [reply lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb]: > Sidenote: I saw you added some comment to make #import <...> the only valid option in CocoaPods 2.0. I think it'll be difficult to get this behavior without silencing the headers (because that's how -isystem works). You'll end up in the invert situation of the one we're in today : pods without silenced warning won't report those warnings in header files (but I may be mistaken, I'm no expert in compiler flags 🙃 ).

I think the (eventual) goal is to make everything either static or dynamic frameworks :)

File: lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb [hunk 2]
```diff
@@ -137,35 +137,55 @@ def embedded_content_settings
...
+          end
+
+          header_search_paths.uniq!
+          silenced_header_search_paths.uniq!
+
+          build_settings = {
+            # TODO: remove quote imports in CocoaPods 2.0
+            # Make headers discoverable with any syntax (quotes, brackets,
+            # @import, etc.)
+            'HEADER_SEARCH_PATHS' => XCConfigHelper.quote(header_search_paths),
```
Comment (segiddins) [inline lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb]: this looks like we'll be adding header search paths even for those things we're adding manually in `OTHER_CFLAGS` ?

Comment (guillaumealgis) [reply lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb]: Yes, to support all import syntaxes. `HEADER_SEARCH_PATHS` makes headers discoverable by `#import "..."`, `#import <...>` and `@import ...`, whereas `-isystem` only works with the `#import <...>` syntax.

So with this patch the `-isystem` and `-iframework` flags we're adding to `HEADER_SEARCH_PATHS ` are not strictly needed for the code to compile, they are just added to silence warnings.

**Comment by guillaumealgis** [comment]
@segiddins I updated the PR and added integrations tests to cover the new behavior.
Please let me know if I need to change anything :)

**Comment by kballard** [comment]
BTW I haven't looked through this PR, but I just hit the underlying issue, and I'm wondering if CocoaPods should also be adding the `[system]` attribute to the module in the modulemap file (when warnings are enabled)? That attribute is basically the module system's equivalent of `-isystem`.

**Comment by dnkoutso** [comment]
@kballard already done at https://github.com/CocoaPods/CocoaPods/pull/7651 for 1.5.1 or 1.6.0

**Comment by evil159** [comment]
What's the status with this PR? Seems like it has been given a green light, I'm sure some people are eagerly awaiting for this.

**Comment by DanToml** [comment]
@evil159 I'm not sure why it never got merged, but it looks like it should be good to go with a rebase.

**Comment by guillaumealgis** [comment]
I'll take a look (not sure when I'll have the time to do this in the next few weeks though).

But to be perfectly honest, if this is too much work (I'm under the impression that a lot changed on how Cocoapods generates build settings since this PR was first implemented) I'm not sure I'll be able to keep pushing this forward. I already rebased multiple times and spent way more time on this than I originally planned to, and since we are no longer using `use_frameworks!` in our product, it's not an issue for us anymore.

I understand though that this issue is still something others would like to see resolved, and that I am probably in the best position to resolve the merge conflicts, so I'll try.

PS: If the tone of my message comes up as angry I'd like to apologize. This is not the case, and I blame my non-native English for the lack of nuance. I'm grateful to the Cocoapods maintainers for their support on this PR, and more globally for working hard on this project and making it awesome 👍

**Comment by dnkoutso** [comment]
@guillaumealgis the blame is on me and we are grateful for your change and patience. My biggest concern has been that this broke Alamofire as per the initial comment but it has been too long since then.

What I wanted to ultimately spend time on was me trying a few pods with this change to ensure they work perhaps the top 10.

**Comment by guillaumealgis** [comment]
I updated the PR to work with the new way of managing build settings. I basically re-wrote it from scratch (but keeping the unit / integration tests mostly unchanged), so I think you should probably take another look at my code :)

What this is doing:
- For non-framework Pods:
    - Add `${PODS_ROOT}/Headers/Public` to `HEADER_SEARCH_PATHS` (no change here)
    - **If the Pod is inhibiting warnings**, add `-isystem ${PODS_ROOT}/Headers/Public/<Podname>` to `OTHER_CFLAGS`
- For framework Pods:
    - Add `${PODS_CONFIGURATION_BUILD_DIR}/<Podname>` to `FRAMEWORK_SEARCH_PATHS` (no change here)
    - Add `${PODS_CONFIGURATION_BUILD_DIR}/<Podname>/Headers` to `HEADER_SEARCH_PATHS ` (kinda new, in master this is done with `-iquote` in `OTHER_CFLAGS`. Result is the same, but it seemed more coherent this way)
    - **If the Pod is inhibiting warnings**, add `-isystem ${PODS_CONFIGURATION_BUILD_DIR}/<Podname>/Headers` and `-iframework ${PODS_CONFIGURATION_BUILD_DIR}/<Podname>` to `OTHER_CFLAGS`

-----------------------------------

Note: I placed my branch in https://github.com/CocoaPods/cocoapods-integration-specs on top of `segiddins/build-phase-ordering` to prevent CI failures.

File: lib/cocoapods/target/build_settings.rb [hunk 3]
```diff
@@ -564,6 +564,12 @@ def initialize(target, test_spec = nil)
           paths
         end
 
+        # @return [String]
+        define_build_settings_method :framework_header_search_paths, :memoized => true do
```
Comment (segiddins) [inline lib/cocoapods/target/build_settings.rb]: nit: it's a single path

**Comment by segiddins** [comment]
@dnkoutso mind testing this out?

File: lib/cocoapods/target/build_settings.rb (hunk 3 above)
Comment (guillaumealgis) [reply lib/cocoapods/target/build_settings.rb]: Just to be sure: You'd rename this `framework_header_search_path` (singular), right?

**Comment by amorde** [comment]
@guillaumealgis thank you so much for continuing to update this PR! there's been some hesitation to merge this as it's hard to be sure that using `-isystem` on pod headers won't have unintended side effects.

That being said, I think we can merge this and hopefully (no promises) release it in another 1.6.0 beta so any issues can be caught. Luckily this only affects pods that are marked with `inhibit_warnings!`, so should any issues arise an easy workaround would be to remove `inhibit_warnings!` while the issue is looked into.

Big thanks again for your work on this 🙏

**Comment by Stitch7** [comment]
I've updated to 1.6.0.beta.2 (from RubyGems) because of this, but it doesn't seem to work here. Already tried cleaning the build folder, deleting my Pods folder and xcworkspace file, but still getting warnings from headers of some of my pods with inhibit_all_warnings! in my Podfile.

I've read 🌈, but it doesn't mention how you handle cases like this. Should i open a new ticket, or do you may reopen already closed ones?

**Comment by guillaumealgis** [comment]
Hi @Stitch7, could you by any chance share the project you're testing this on?
If not, could you send a list of the warnings you are getting please? Thanks!

**Comment by adellibovi** [comment]
In my case it worked for most cases, only the "documentation warnings" are kept out. Good job @guillaumealgis  :)

**Comment by guillaumealgis** [comment]
@adellibovi thank you :)
This should not happen though, documentation warnings should be silenced too. Could you share your project / a reproducible example please?

**Comment by Stitch7** [comment]
Hi @guillaumealgis, thanks for your quick response.
While i was trying to create a new iOS project from Xcode template to share with only the Pods having warnings, i noticed that in this case, with a fresh project, there are no warnings after build from my problematic pods.
But i can also share my real project because it's [here on github](https://github.com/Stitch7/mclient)
Maybe it's my mistake and i've something wrong in my build settings overwriting something?

**Comment by guillaumealgis** [comment]
Great, thank you @Stitch7 ! I'll try to take a look at it this weekend.

**Comment by adellibovi** [comment]
> @adellibovi thank you :)
> This should not happen though, documentation warnings should be silenced too. Could you share your project / a reproducible example please?

Actually I found out the issue in this project the include was done by #import "foo.h" and not #import <foo.h> :) So works fine!

**Comment by guillaumealgis** [comment]
Hehe thanks for the feedback @adellibovi. Still, both `#import` syntaxes should be supported by this fix. I'll take a look (if you can share a project / reproducible example I'd be grateful 😌).

**Comment by guillaumealgis** [comment]
@adellibovi I'm guessing your have `use_modular_headers!` in your Podfile?

I think modulemap are the problem here. using `#import <...>` solves the problem because then the compile treats the module-map as a system one and silences warnings.

I'll dig the LLVM documentation on modules, but I'm not sure if we can force a module-map to be treated as a system one when using the `import "..."` syntax.

**Comment by kballard** [comment]
Module maps can use the `[system]` attribute on a `module` declaration to declare that it's a system module.

**Comment by segiddins** [comment]
Unfortunately, the system attributes changes how NSUIntegers are imported. (We originally used it when the feature was first introduced, then had to roll it back because it broke source compatibility)

**Comment by guillaumealgis** [comment]
@segiddins That's unfortunate. I suppose we're forced to keep the current behavior where only `import <...>` silences warnings for modular headers then?

**Comment by minuscorp** [comment]
The only working solution I've found is to add `#pragma clang diagnostic ignored "-Wno-nonnull"` to the project's bridging header
