### PR TITLE
Fix repo lint for path arguments

### LINKED ISSUE #4883: `pod repo lint` seems broken in 1.0 betas
When linting a checkout of <https://github.com/contentful/CocoaPodsSpecs>:

```bash
$ pod repo lint .

Linting spec repo `repos`

[!] An unexpected version directory `Artsy+Authentication` was encountered for the `/Users/boris/.cocoapods/repos/artsy` Pod in the `artsy` repository.
```

Expected behaviour (what happened with 0.39.0 and earlier):

```
$ pod repo lint .

Linting spec repo `CocoaPodsSpecs`

.................

-> Warnings must not be disabled(`-Wno compiler` flags).
  - cmark (0.22.0, 0.17)

Analyzed 17 podspecs files.

All the specs passed validation.
```

Basically seems like linting a directory no longer works.

### PR DESCRIPTION
**Pull request by neonichu**
Fixes #4883

### CODE REVIEW

File: lib/cocoapods/command/repo/lint.rb [hunk 1]
```diff
@@ -35,16 +35,20 @@ def initialize(argv)
         #
         def run
           if @name
```
Comment (segiddins) [inline lib/cocoapods/command/repo/lint.rb]: this can only assign once,  by assigning the result of the conditional to `sources`

**Comment by segiddins** [comment]
:+1: other than the one comment

File: lib/cocoapods/command/repo/lint.rb (hunk 1 above)
Comment (neonichu) [inline lib/cocoapods/command/repo/lint.rb]: TIL
