### PR TITLE
Fix cross-project framework dependencies

### LINKED ISSUE #6123: No 'Embed Pods frameworks' build phase when building custom framework ?
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

I use CocoaPods in a project where we separate core material from app material.  
Inside our workspace there are 3 projects (not counting Pods project), one for the core, and 2 others, one for the iOS version and another macOS version of the app.

The core project builds a framework which as dependencies. Those dependencies should be copied into a folder named `Frameworks`, but are not.
Indeed, there is no 'Embed Pods Frameworks' build phase for the core framework target.
(There is one however for the core framework test target).

Everything builds fine, but when I launch the app, the loader complains it can't load frameworks :
```
dyld: Library not loaded: @rpath/Alamofire.framework/Versions/A/Alamofire
  Referenced from: /Users/vince/Library/Developer/Xcode/DerivedData/App-ggigklukffxidydygewgkvwmfwbl/Build/Products/Debug/AppCore.framework/Versions/A/AppCore
  Reason: image not found
```

I'm looking for a way to copy those dependencies inside the framework bundle.

## What did you do?

Run `pod install` inside the directory where the `Podfile` file is.
Open the workspace, build and run the macOS target (same crash for iOS)

If I copy the script inside the 'Embed Pods Frameworks' build phase for the tests target, into a new script build phase for the core framework, it does work (dependencies are copied, no loading error).

## What did you expect to happen?

I expected the app to run, without error.

## What happened instead?

The loader cannot locate and load a framework dependency inside my core framework.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.8
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /Users/vince/.rvm/rubies/ruby-2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d006285cac32ca0ec77dafe98114de840ace76a3
```

### Installation Source

```
Executable Path: /Users/vince/.rvm/gems/ruby-2.2.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
workspace './App.xcworkspace'

use_frameworks!
inhibit_all_warnings!

abstract_target 'App Core' do

pod 'LzmaSDK-ObjC'
pod 'Moya', '~> 8.0.0-beta.3'

target :'App Core macOS' do
    project './App Core/App Core.xcodeproj'
    platform :osx, '10.11'

    target 'App Core macOSTests' do
        inherit! :search_paths
    end
end

target :'App Core iOS' do
    project './App Core/App Core.xcodeproj'
    platform :ios, '9.0'

    target 'AppCore Core iOSTests' do
        inherit! :search_paths
    end
end

end

abstract_target 'App Apps' do

    pod 'Fabric'
    pod 'Crashlytics'

  target :'App macOS' do
    project './App macOS/App macOS.xcodeproj'
    platform :osx, '10.11'

    target 'App macOSTests' do
      inherit! :search_paths
    end
  end

  target :'App iOS' do
    project './App iOS/App iOS.xcodeproj'
    platform :ios, '9.0'

    target 'App iOSTests' do
      inherit! :search_paths
    end
  end

end
```

### PR DESCRIPTION
**Pull request by benasher44**
Fixes #6123 

I fixed `copy_embedded_target_pod_targets_to_host` to properly handle embedded targets that live in another project. I don't think this has worked properly on master. From what I can gather, the way that I originally wrote the test convinced me that this was working. My best guess is that the version of this that I had people asking about this test (and worked) changed during the PR and didn't end up being exactly what made it into master. This fixes the test (verified it failed before), and then it fixes `copy_embedded_target_pod_targets_to_host`.

### CODE REVIEW

**Comment by benasher44** [comment]
No more tweaks coming here, so this is ready to go. I have a sample project up that uses this PR here: https://github.com/benasher44/CocoaPodsLibExample

File: lib/cocoapods/installer/analyzer.rb [hunk 1]
```diff
@@ -238,18 +238,20 @@ def update_repositories
...
         return if aggregate_target.requires_host_target?
-        # Get the uuids of the aggregate_target's user_targets' embedded targets if any
-        embedded_uuids = Set.new(aggregate_target.user_targets.map do |target|
-          aggregate_target.user_project.embedded_targets_in_native_target(target).map(&:uuid)
-        end.flatten)
-        return if embedded_uuids.empty?
-        embedded_aggregate_targets.each do |embedded_target|
-          next unless embedded_target.user_targets.map(&:uuid).any? do |embedded_uuid|
-            embedded_uuids.include? embedded_uuid
+        pod_target_names = Set.new aggregate_target.pod_targets.map(&:name)
```
Comment (DanToml) [inline lib/cocoapods/installer/analyzer.rb]: parens around args to `Set.new`

File: lib/cocoapods/installer/analyzer.rb [hunk 2]
```diff
@@ -238,18 +238,20 @@ def update_repositories
...
+        aggregate_user_target_uuids = Set.new aggregate_target.user_targets.map(&:uuid)
+        embedded_aggregate_targets.each do |embedded_aggregate_target|
+          next unless embedded_aggregate_target.user_targets.any? do |embedded_user_target|
+            # You have to ask the host target's project for the host targets of
+            # the embedded target, as opposed to asking user_project for the
+            # embedded targets of the host target. The latter doesn't work when
+            # the embedded target lives in a sub-project. The line below gets
+            # the host target uuids for the embedded target and checks to see if
+            # those match to any of the user_target uuids in the aggregate_target.
+            !aggregate_user_target_uuids.intersection(Set.new(aggregate_target.user_project.host_targets_for_embedded_target(embedded_user_target).map(&:uuid))).empty?
```
Comment (DanToml) [inline lib/cocoapods/installer/analyzer.rb]: could you break this into a set assignment and the intersection?

Comment (benasher44) [inline lib/cocoapods/installer/analyzer.rb]: I originally didn't because I thought rubocop would complain about unneeded variable assignment (or something to that effect), but it didn't! This is much better.
