### PR TITLE
Output Swift targets when multiple versions of Swift are detected.

### LINKED ISSUE #6191: pod update fails with "There may only be up to 1 unique SWIFT_VERSION per target"
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod update`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Pods fail to update.

```
$ pod update
Update all pods
Updating local specs repositories

CocoaPods 1.2.0.beta.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.2.0.beta.1

Analyzing dependencies
[!] There may only be up to 1 unique SWIFT_VERSION per target.
```

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.10.2
Ruby lib dir : /Users/dan/.rbenv/versions/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f36294f4c598ecb4a8a7ba7d1e99944f0eb16e77
               wepay - git@github.com:wepay/mobile-podspecs.git @ 277fce1c76ad03b4063800cea89e041ac1a7d12e
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-playgrounds : 1.2.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
project 'My App.xcodeproj'

inhibit_all_warnings!
use_frameworks!

target 'My App' do
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireImage', '~> 3.0'
  pod 'AlamofireNetworkActivityIndicator', '~> 2.0'

  pod 'LionheartExtensions', '~> 2.0'
  pod 'LionheartAlamofireClient', '~> 2.1'
  pod 'QuickTableView', '~> 2.0'
  pod 'LionheartCurrencyTextField', '~> 1.0'

  pod 'TableViewPopoverPresenting', '~> 2.0'
  pod 'FMDB/standalone/FTS', '~> 2.6'
  pod 'KeyboardAdjuster', '~> 1.3'
  pod 'Signature'
  pod 'SHSPhoneComponent'
  pod 'ReachabilitySwift', '~> 3.0'
  pod 'libPhoneNumber-iOS', '~> 0.8'
  pod 'SwiftyUserDefaults', '~> 3.0'

  pod 'Raygun4iOS'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Mixpanel'
  pod 'Zip'
  pod 'SentrySwift'

  target 'My App Tests' do
    inherit! :search_paths

    pod 'Nimble', '~> 5.1'
  end
end
```

### PR DESCRIPTION
**Pull request by dnkoutso**
closes #6191 

/cc @justinseanmartin @benasher44 

Output looks like:

```
There may only be up to 1 unique SWIFT_VERSION per target. Found target(s) with multiple Swift versions:
Target: Swift 2.3
Target2: Swift 3.0
```

### CODE REVIEW

File: lib/cocoapods/installer/analyzer/target_inspector.rb [hunk 1]
```diff
@@ -216,16 +216,22 @@ def compute_recommends_frameworks(target_definition, native_targets)
...
+
+          case versions_to_targets.count
           when 0
             nil
           when 1
-            versions.first
+            versions_to_targets.keys.first
           else
-            raise Informative, 'There may only be up to 1 unique SWIFT_VERSION per target.'
+            raise Informative, "There may only be up to 1 unique SWIFT_VERSION per target. Found target(s) with multiple Swift versions:\n#{JSON.pretty_generate(versions_to_targets)}"
```
Comment (benasher44) [inline lib/cocoapods/installer/analyzer/target_inspector.rb]: Minor issue: Can we have the output formatting just be a newline separated list of <targetname>: Swift <version> ? I think this would be easier to read at first glance.

**Comment by dnkoutso** [comment]
Updated.

**Comment by justinseanmartin** [comment]
LGTM too

**Comment by orta** [comment]
This feels good to me 👍

**Comment by dnkoutso** [comment]
Not sure why that test failed...rebased and trying again...

**Comment by DanToml** [comment]
@dnkoutso The file_accessor spec doesn't sort the output headers, and relies on file system ordering of the vendored_framework_headers_dir, so it doesn't seem to be caused by this.

**Comment by dnkoutso** [comment]
yay green.
