### PR TITLE
Fix processing of xcassets resources when pod target is static framework

### LINKED ISSUE #10170: Pods-<target>-resources.sh contains incorrect assets path
🌈
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Tried to build a project with a dev pod containing `.xcassets` file, using statically-linked frameworks.

## What did you expect to happen?

Expected the project to build successfully.

## What happened instead?

Got an error during the `[CP] Copy Pods Resources` build phase:
```
error: Resource "/Users/federicotrimboli/Library/Developer/Xcode/DerivedData/AssetsBug-daxuxarxrtwbxadonvosjaawkieq/Build/Products/Debug-iphonesimulator/DevPod/DevPod.framework/Images.car" not found. Run 'pod install' to update the copy resources script.
```

The original `.xcassets` file included in the dev pod is indeed called `Images.xcassets`, but when navigating to the path shown in the error, I can see that the compiled `.car` file is actually called `Assets.car`. Looks like Xcode assigns `Assets.car` to every compiled `xcassets` regardless of the original name. However, the `Pods-<target>-resources.sh` script tries to access the file using the original name `Images` instead of `Assets`.

Additionally, if there were more than one `xcassets`, all of them would be merged+compiled into a single `Assets.car`, so the naming makes sense. In this case, the script should contain a single line but instead it's generating one line per `xcassets` file.

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.7 (19H2)
       Xcode : 12.0.1 (12A7300)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/federicotrimboli/.rvm/rubies/ruby-2.6.3/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ af326a1bd1b3bbe0188e494fc00d6355e455e836

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/federicotrimboli/.rvm/gems/ruby-2.6.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
unless defined?(Bundler)
  puts "\nPlease re-run using:".red
  puts "  bundle exec pod #{ARGV.join(' ')}\n"
  exit(1)
end

install! 'cocoapods'
platform :ios, '12.0'
use_frameworks! :linkage => :static

target 'AssetsBug' do
  pod 'DevPod', :path => 'DevPod'
end
```

## Project that demonstrates the issue

I'm attaching a sample Xcode project that demonstrates the issue: [AssetsBug.zip](https://github.com/CocoaPods/CocoaPods/files/5438117/AssetsBug.zip)

### PR DESCRIPTION
**Pull request by fedetrim**
#9441 introduced an optimization for static framework pod targets by copying compiled resources (storyboards, xcdatamodels, etc) instead of the original resources and therefore avoiding duplicate work (once in the framework's `Copy Bundle Resources` phase, and another in the final target's integration phase `[CP] Copy Pods Resources`).

This optimization assumes that each `<name>.xcassets` has a compiled `<name>.car` counterpart, and that you can have many `.car` files in a single bundle.
However, in reality, all `<name>.xcassets` from the same framework are merged and compiled into a single `Assets.car`, meaning that the  `[CP] Copy Pods Resources` integration phase is failing because it's not able to find the compiled resources:
Screen Shot 2020-10-28 at 16 58 31

With the failing piece of code being within `Pods-<target>-resources.sh`:
```ruby
if [[ "$CONFIGURATION" == "Debug" ]]; then
  install_resource "${BUILT_PRODUCTS_DIR}/DevPod/DevPod.framework/AnotherOne.car"
  install_resource "${BUILT_PRODUCTS_DIR}/DevPod/DevPod.framework/Images.car"
fi
```

In order for that to not fail, it should look like this:
```ruby
if [[ "$CONFIGURATION" == "Debug" ]]; then
  install_resource "${BUILT_PRODUCTS_DIR}/DevPod/DevPod.framework/Assets.car"
fi
```

Even if we addressed that issue by correcting the path of the compiled resources, we still wouldn't be able to copy more than one `Assets.car` (one per each framework) to the main bundle.

The only way of handling xcassets is by merging+building them all at once, and then copying that single `Assets.car` to the main bundle (which is what was being done before this optimization).

This PR solves the issue by adding the original xcassets back to being processed by the `[CP] Copy Pods Resources` integration phase, and removes the resources from the frameworks' `Copy Bundle Resources` phase so that the compiling is only done once.

Closes #10170

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Fix processing of xcassets resources when pod target is static framework  
  [fedetrim](https://github.com/fedetrim)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by igor-makarov** [comment]
Hi @fedetrim!

I think the change you're proposing is valid - asset catalogs and static frameworks probably never worked right before.

However, I think the right place to introduce the check is in `Pod::Target#resource_extension_compilable?` - there are two places the function is called and both need this change.

**Comment by fedetrim** [comment]
@igor-makarov thanks for reviewing!

> However, I think the right place to introduce the check is in Pod::Target#resource_extension_compilable? - there are two places the function is called and both need this change.

I had tried that first and it didn't work -- however I just tried again and it did! Probably did something differently the first time.
Anyway, just pushed the change :)

**Comment by igor-makarov** [comment]
@fedetrim excellent - could you please add some tests for this case?

**Comment by fedetrim** [comment]
@igor-makarov done

File: spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb [hunk 1]
```diff
@@ -762,6 +762,15 @@ class PodsProjectGenerator
...
 
+            it 'doesn\'t add xcassets resources to the static framework target' do
+              @pod_target.stubs(:build_type => BuildType.static_framework)
+              @installer.install!
+              resources = @project.targets.first.resources_build_phase.files
+              resources.count.should > 0
+              resource = resources.find { |res| res.file_ref.path.include?('Images.xcassets') }
+              resource.should.be.nil
+            end
+
```
Comment (igor-makarov) [inline spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb:773]: Could you add one more? For the dynamic framework, ensuring it does add the asset catalog?

Comment (fedetrim) [reply spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb:773]: good idea, done! 😄

**Comment by dnkoutso** [comment]
@fedetrim can you rebase and point to the `1-10-stable` branch instead? We want to ship this with 1.10.1 version.

**Comment by fedetrim** [comment]
@dnkoutso
>can you rebase and point to the 1-10-stable branch instead?

Done 👍
Thanks for reviewing!

**Review by dnkoutso — APPROVED** [review]

**Comment by dnkoutso** [comment]
thanks!
