### PR TITLE
Better static frameworks transitive dependency error checking

### LINKED ISSUE #7352: xcode build failed when I use 'static_framework' . ld: library not found for
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I pod update and build.

## What did you expect to happen?
xcode build success.

## What happened instead?
xcode build failed.

### Stack

```
   CocoaPods : 1.4.0.rc.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.2 (17C205)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /Users/admin/.rvm/rubies/ruby-2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6b109f6d5c3ca99638bdc82062848e081d03d191
```

### Installation Source

```
Executable Path: /Users/admin/.rvm/gems/ruby-2.4.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AAAA' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for AAAA
  pod 'A',:path => 'A.podspec'
  pod 'B',:path => 'B.podspec'

end
```

## Project that demonstrates the issue

[AAAA.zip](https://github.com/CocoaPods/CocoaPods/files/1648770/AAAA.zip)

### PR DESCRIPTION
**Pull request by paulb777**
Generate an error for transitive dependencies from dynamic libraries to static frameworks.

Close #7352

### CODE REVIEW

File: lib/cocoapods/installer/xcode/target_validator.rb [hunk 1]
```diff
@@ -71,16 +71,22 @@ def verify_no_static_framework_transitive_dependencies
...
+              dependencies = dynamic_pod_targets.select(&:should_build?).flat_map(&:dependencies)
+              depended_upon_targets = dynamic_pod_targets.select { |t| dependencies.include?(t.pod_name) && !t.should_build? }
 
               static_libs = depended_upon_targets.flat_map(&:file_accessors).flat_map(&:vendored_static_artifacts)
               unless static_libs.empty?
                 raise Informative, "The '#{aggregate_target.label}' target has " \
                   "transitive dependencies that include static binaries: (#{static_libs.to_sentence})"
               end
+
+              static_framework_deps = dynamic_pod_targets.select(&:should_build?).flat_map(&:recursive_dependent_targets).select(&:static_framework?)
```
Comment (segiddins) [inline lib/cocoapods/installer/xcode/target_validator.rb]: in theory, it's ok for this to not be empty, so long as each static framework is only linked into _exactly one_ dynamic binary -- that binary need not be the user target

Comment (paulb777) [reply lib/cocoapods/installer/xcode/target_validator.rb]: Maybe in theory - although I'm not a 100% convinced.  Is a compile for a static object always relocatable? It's not necessarily so and definitely isn't in some ABIs. Even so, it's not supported by the implementation as demonstrated by #7352.

I propose we go ahead with this PR since it makes static_framework transitive checking consistent with binary vendored static frameworks.

We could follow up on this point in a future PR.

Comment (segiddins) [reply lib/cocoapods/installer/xcode/target_validator.rb]: Yeah, this is good as is! Just wanted to point out that edge case

**Comment by dnkoutso** [comment]
Le merging!
