### PR TITLE
Fix static_framework Swift pod deps and pod access to dep vendored modules

### LINKED ISSUE #7117: Using static framework gives error
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Created a pod that has static_framework=true and added dependencies

## What did you expect to happen?

To build successfully

## What happened instead?

Getting error
screen shot 2017-10-10 at 9 41 11 am

### Stack

```
   CocoaPods : 1.4.0.beta.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.1_1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c9ae2b83739d682b3957c23f56e683d3f19a0053
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.2
cocoapods-deintegrate  : 1.0.1
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-playgrounds  : 1.2.2
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.3.0
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
```

## Project that demonstrates the issue

https://github.com/mukeshthawani/TestStaticFramework

### PR DESCRIPTION
**Pull request by paulb777**
Fixes #7117 

This PR fixes/implements two issues:

1. When I implemented static frameworks, I made the incorrect assumption that static_frameworks don't need to worry about build dependencies because they don't link. That's not the case when a static_framework depends upon a Swift CocoaPod where it needs its bridging header to be built. This is fixed by the conditional change in `lib/cocoapods/installer/xcode/pods_project_generator.rb`.

2. CocoaPods did not support importing modules from vendored frameworks. While this is annoying for Objective C, it's a show stopper for a Swift CocoaPod depending on a vendored framework.  The vendored framework modules were not being added to FRAMEWORK_SEARCH_PATHS for pod builds that depended upon them. I added a call in `lib/cocoapods/generator/xcconfig/pod_xcconfig.rb` to `generate_vendored_build_settings`. Most of the changes to `lib/cocoapods/generator/xcconfig/xcconfig_helper.rb` are renaming and filtering so that FRAMEWORK_SEARCH_PATHS can be updated with or without updating OTHER_LD_FLAGS.

### CODE REVIEW

File: lib/cocoapods/generator/xcconfig/pod_xcconfig.rb [hunk 1]
```diff
@@ -71,6 +71,7 @@ def generate
           XCConfigHelper.add_target_specific_settings(target, @xcconfig)
           recursive_dependent_targets = target.recursive_dependent_targets
           @xcconfig.merge! XCConfigHelper.search_paths_for_dependent_targets(target, recursive_dependent_targets, @test_xcconfig)
+          XCConfigHelper.generate_vendored_build_settings(target, recursive_dependent_targets, @xcconfig, false)
```
Comment (dnkoutso) [inline lib/cocoapods/generator/xcconfig/pod_xcconfig.rb]: should this always happen for all pod targets? For example what if someone does not use `use_frameworks!` and instead use static libs? Does the same apply?

File: lib/cocoapods/installer/xcode/pods_project_generator.rb [hunk 2]
```diff
@@ -229,10 +229,11 @@ def set_target_dependencies
               aggregate_target.native_target.add_dependency(pod_target.native_target)
               configure_app_extension_api_only_for_target(pod_target) if is_app_extension
 
+              add_dependent_targets_to_native_target(pod_target.dependent_targets,
```
Comment (dnkoutso) [inline lib/cocoapods/installer/xcode/pods_project_generator.rb]: is there a test that covers this case?

**Comment by dnkoutso** [comment]
The `xcconfig_helper.rb` is getting convoluted. I've been thinking of redesigning a lot of it, perhaps by providing an "IntegrationStrategy" class in which different pod targets are integrated differently (static lib, static framework, dynamic framework etc.)

Not for now just vending on the complexity of `xcconfig_helper.rb`

File: lib/cocoapods/generator/xcconfig/pod_xcconfig.rb (hunk 1 above)
Comment (paulb777) [reply lib/cocoapods/generator/xcconfig/pod_xcconfig.rb]: Good catch! I added the check. 

It also changed the back the different order on the `adds settings for test dependent targets excluding the parents targets` unit test to being unchanged from master

File: lib/cocoapods/installer/xcode/pods_project_generator.rb (hunk 2 above)
Comment (paulb777) [reply lib/cocoapods/installer/xcode/pods_project_generator.rb]: I haven't been able to figure out how the tests in `pods_project_generator_spec.rb` do validation to test Xcode project contents. 

Do you have any guidance?

**Comment by paulb777** [comment]
Agreed on the need to rework `xcconfig_helper.rb` and the defining of `FRAMEWORK_SEARCH_PATHS` and 'OTHER_LD_FLAGS`

File: lib/cocoapods/installer/xcode/pods_project_generator.rb (hunk 2 above)
Comment (dnkoutso) [reply lib/cocoapods/installer/xcode/pods_project_generator.rb]: Ah yes I remember now this is a bit difficult to write but doable.

Look into:
```ruby
          describe '#set_test_target_dependencies' do
            ...
          end
```
Most of it is mocked and ensures all mocks receive the correct method calls with parameters.

File: spec/unit/generator/xcconfig/pod_xcconfig_spec.rb [hunk 3]
```diff
@@ -75,6 +101,23 @@ module XCConfig
...
+          it 'sets the framework search paths' do
+            @xcconfig.to_hash['FRAMEWORK_SEARCH_PATHS'].should.include('spec/fixtures/banana-lib')
+            @xcconfig.to_hash['FRAMEWORK_SEARCH_PATHS'].should.include('spec/fixtures/monkey')
+            @xcconfig.to_hash['FRAMEWORK_SEARCH_PATHS'].should.include('${PODS_ROOT}/AAA')
+            @xcconfig.to_hash['FRAMEWORK_SEARCH_PATHS'].should.not.include('${PODS_ROOT}/BBB')
+            @xcconfig.to_hash['FRAMEWORK_SEARCH_PATHS'].should.include('${PODS_ROOT}/CCC')
+            @xcconfig.to_hash['FRAMEWORK_SEARCH_PATHS'].should.not.include('${PODS_ROOT}/DDD')
+          end
+
+          it 'it vendored frameworks dont get added to frameworks paths if use_frameworks! isnt set' do
```
Comment (dnkoutso) [inline spec/unit/generator/xcconfig/pod_xcconfig_spec.rb]: nit: remove second `it`

File: CHANGELOG.md [hunk 4]
```diff
@@ -8,6 +8,10 @@ To install release candidates run `[sudo] gem install cocoapods --pre`
 
 ##### Enhancements
 
+* Fix static_framework Swift pod dependencies and implement pod access to dependent vendored_framework modules
```
Comment (dnkoutso) [inline CHANGELOG.md]: nit: probably place this in the `Bug Fixes` section can include #7117 link instead

File: lib/cocoapods/installer/xcode/pods_project_generator.rb (hunk 2 above)
Comment (paulb777) [reply lib/cocoapods/installer/xcode/pods_project_generator.rb]: Thanks! That helped.

File: lib/cocoapods/generator/xcconfig/xcconfig_helper.rb [hunk 5]
```diff
@@ -103,16 +106,18 @@ def self.add_settings_for_file_accessors_of_target(aggregate_target, pod_target,
...
+        #
         # @return [void]
         #
-        def self.add_static_dependency_build_settings(aggregate_target, pod_target, xcconfig, file_accessor)
-          if aggregate_target.nil? || !file_accessor.spec.test_specification?
+        def self.add_static_dependency_build_settings(target, pod_target, xcconfig, file_accessor, include_ld_flags)
+          if target.nil? || !file_accessor.spec.test_specification?
+            adds_other_ldflags = include_ld_flags && XCConfigHelper.links_dependency?(target, pod_target)
             file_accessor.vendored_static_frameworks.each do |vendored_static_framework|
-              adds_other_ldflags = XCConfigHelper.links_dependency?(aggregate_target, pod_target)
```
Comment (dnkoutso) [inline lib/cocoapods/generator/xcconfig/xcconfig_helper.rb]: ha good catch, no need to call this twice

**Comment by dnkoutso** [comment]
ah sorry @paulb777 I merged the other PR first and this one needs rebase.

**Comment by paulb777** [comment]
np @dnkoutso I needed to squash anyways.

It's now squashed and rebased and should be good to go on green.

Thanks for the prompt, helpful reviews today! 👍

**Comment by mukeshthawani** [comment]
Thanks @paulb777 for fixing this, I will give it a try and let you know.
