### PR TITLE
Fix 1.7.0.rc.1 static library regression for header_dir attribute

### LINKED ISSUE #8765: 1.7.0.rc1 regression on static library build HEADER_SEARCH_PATHS
#8706 breaks the static library builds of `FirebaseDatabase` and `FirebaseFirestore`. `FirebaseDatabase` fails with 

```
Firebase/Database/third_party/Wrap-leveldb/APLevelDB.mm:54:9: fatal error: 'leveldb/db.h' file not found
#import "leveldb/db.h"
```
because the public headers from the leveldb-library pod are no longer in `HEADER_SEARCH_PATHS`:

```
diff -r good-Pods/Target Support Files/FirebaseDatabase/FirebaseDatabase.xcconfig Pods/Target Support Files/FirebaseDatabase/FirebaseDatabase.xcconfig
4c4
< HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Private" "${PODS_ROOT}/Headers/Private/FirebaseDatabase" "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/FirebaseAuthInterop" "${PODS_ROOT}/Headers/Public/FirebaseCore" "${PODS_ROOT}/Headers/Public/FirebaseDatabase" "${PODS_ROOT}/Headers/Public/GoogleUtilities" "${PODS_ROOT}/Headers/Public/leveldb-library"
---
> HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Private" "${PODS_ROOT}/Headers/Private/FirebaseDatabase" "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/FirebaseAuthInterop" "${PODS_ROOT}/Headers/Public/FirebaseCore" "${PODS_ROOT}/Headers/Public/FirebaseDatabase" "${PODS_ROOT}/Headers/Public/GoogleUtilities"
```

To reproduce, put pod `FirebaseDatabase` in a Podfile without `use_frameworks!`, pod install, and build.

### PR DESCRIPTION
**Pull request by paulb777**
Fix #8765

#8706 introduced a bug building pods with the `header_dir` attribute as static libraries. This is a minimal fix for that issue.

### CODE REVIEW

File: lib/cocoapods/target/pod_target.rb [hunk 1]
```diff
@@ -150,7 +150,11 @@ def all_files
     # @return [Pathname] the pathname for headers in the sandbox.
     #
     def headers_sandbox
-      Pathname.new(product_module_name)
+      if root_spec.attributes_hash.key?('header_dir')
```
Comment (amorde) [inline lib/cocoapods/target/pod_target.rb]: we might want something a bit more robust for this in the future (maybe `root_spec.consumer(platform).header_dir`?) but this should work for now

Comment (dnkoutso) [reply lib/cocoapods/target/pod_target.rb]: yes can we use `consumer` here?

Comment (paulb777) [reply lib/cocoapods/target/pod_target.rb]: My first attempt to use `consumer` generated a bunch of test failures. I'll make another attempt to work though them later on today.

Comment (paulb777) [reply lib/cocoapods/target/pod_target.rb]: Why is using `consumer` more robust?

Comment (amorde) [reply lib/cocoapods/target/pod_target.rb]: My thought was it would remove the reliance on knowing the structure of attributes_hash, but I can see how that’s not really a problem in practice

Comment (paulb777) [reply lib/cocoapods/target/pod_target.rb]: I suppose it's at least a consistent style to use `consumer`. I made the update.

**Comment by dnkoutso** [comment]
consumer will also take care of multi-platform and automatic default wrapper etc.
