### PR TITLE
Fix an issue that caused stale framework artifacts when archiving

### LINKED ISSUE #9458: While using XCFramework as a vendored_framework, Instead of IOS Archive, It is generating the Generic Xcode Archive.
Hi, 

# Report

## What did you do?

ℹ I have created XCFramework, that one I added as `vendored_frameworks` and distributed in cocoapods.

## What did you expect to happen?

ℹ Once we install that pod into the client's IOS projects, It is working fine when running into a simulator or real device. But when we create the archive it is expected to create` IOS Archive`.

## What happened instead?

ℹ Instead of `IOS Archive`, It is generating the `Generic Xcode Archive`. When we use .framework file, it is working fine. Problem with XCFramework only. 

## CocoaPods Environment

ℹ CocoaPods version **1.9.0.beta.2**
ℹ  Xcode Version - 11.2.1

## Project that demonstrates the issue

ℹ I have verified this repo also [cocoapods integration repo](https://github.com/CocoaPods/cocoapods-integration-specs/tree/master/install_vendored_xcframework). The Same problem.

ℹ Try with this also `pod 'CoconutLib'`

* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

@amorde Please help me to resolve this issue. I looking forward to hearing from you. If you need more information let me know.

### PR DESCRIPTION
**Pull request by amorde**
Closes #9458 

Requires https://github.com/CocoaPods/cocoapods-integration-specs/pull/264

When archiving, the `.framework` slice that was placed in `Prepare Artifacts` was left in the `Products/Applications` directory of the archive because that is what `${TARGET_BUILD_DIR}` is set to when archiving. During a non-install build, the value matches that of `${CONFIGURATION_BUILD_DIR}`

### CODE REVIEW

File: lib/cocoapods/generator/prepare_artifacts_script.rb [hunk 1]
```diff
@@ -117,7 +117,7 @@ def script
             fi
 
             local record_artifact=${2:-true}
-            local destination="${TARGET_BUILD_DIR}"
+            local destination="${CONFIGURATION_BUILD_DIR}"
```
Comment (dnkoutso) [inline lib/cocoapods/generator/prepare_artifacts_script.rb]: shouldnt we use something like `BUILT_PRODUCTS_DIR`?

Comment (amorde) [reply lib/cocoapods/generator/prepare_artifacts_script.rb]: Hmm not sure, they seem to be the same in my tests. Here's the docs for each

> Per-configuration Build Products Path (CONFIGURATION_BUILD_DIR)
The base path where build products will be placed during a build for a given configuration. By default, this is set to $(BUILD_DIR)/$(CONFIGURATION).

> BUILT_PRODUCTS_DIR
Identifies the directory under which all the product’s files can be found. This directory contains either product files or symbolic links to them. Run Script build phases can use the value of this build setting as a convenient way to refer to the product files built by one or more targets even when these files are scattered throughout a directory hierarchy (for example, when Deployment Location (DEPLOYMENT_LOCATION) is set to YES.

We've used `${CONFIGURATION_BUILD_DIR}` elsewhere such as https://github.com/CocoaPods/CocoaPods/blob/42741d897eb8ab34f9a1524988f59ff3f7760cc4/lib/cocoapods/generator/embed_frameworks_script.rb#L63

Comment (dnkoutso) [reply lib/cocoapods/generator/prepare_artifacts_script.rb]: sg!

File: CHANGELOG.md [hunk 2]
```diff
@@ -10,14 +10,18 @@ To install release candidates run `[sudo] gem install cocoapods --pre`
 
 * PathList optimizations related to file system reads.  
   [manuyavuz](https://github.com/manuyavuz)
-  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/4927)
+  [#4927](https://github.com/CocoaPods/CocoaPods/issues/4927)
```
Comment (dnkoutso) [inline CHANGELOG.md]: I can fix this in a separate commit!

File: lib/cocoapods/generator/prepare_artifacts_script.rb (hunk 1 above)
Comment (dnkoutso) [reply lib/cocoapods/generator/prepare_artifacts_script.rb]: I think its good because I think `CONFIGURATION_BUILD_DIR` is on a per-target basis while `BUILT_PRODUCTS_DIR` is global.

**Comment by dnkoutso** [comment]
Merged integration specs, needs rebase and update of submodule sha and we can merge!

File: lib/cocoapods/generator/prepare_artifacts_script.rb (hunk 1 above)
Comment (amorde) [reply lib/cocoapods/generator/prepare_artifacts_script.rb]: oh nice, TIL

Comment (dnkoutso) [reply lib/cocoapods/generator/prepare_artifacts_script.rb]: well this is how I read it from what you pasted above :D

Comment (amorde) [reply lib/cocoapods/generator/prepare_artifacts_script.rb]: I initially read "the product's file" as a single product but I realize now it mentions other targets
