### PR TITLE
Better vendored framework support

### LINKED ISSUE #1993: `vendored_frameworks` should automatically get embedded appropriately.
From @alloy originally submitted to CocoaPods/Core#58

--

This means that the framework should:

- [ ] Automatically get copied into the app bundle in the Frameworks dir.
- [x] Automatically configure the application to load frameworks from the Frameworks dir, if they use `@rpath`.
- [ ] For iOS frameworks, simulator slices need to be removed when creating an Archive build, because otherwise App Store will reject the binary.
- [x] Ensure that embedded frameworks are code-signed if necessary.
- [ ] Allow transitive dependencies upon vendored frameworks, by correctly setting `FRAMEWORK_SEARCH_PATH` for user targets (see [this comment](https://github.com/CocoaPods/CocoaPods/pull/3604#issuecomment-107400685))

Currently you have to do the following:

```ruby
  s.osx.vendored_framework = "PLCrashReporter-1.2-rc2/Mac OS X Framework/CrashReporter.framework"
  s.osx.resource = "PLCrashReporter-1.2-rc2/Mac OS X Framework/CrashReporter.framework"
  s.osx.xcconfig = { 'LD_RUNPATH_SEARCH_PATHS' => '@loader_path/../Frameworks' }
```

--

Related to:

- https://github.com/CocoaPods/CocoaPods/issues/1992
- https://github.com/CocoaPods/CocoaPods/issues/1824
- #3015 (same problem on iOS 8 and above)

### PR DESCRIPTION
**Pull request by segiddins**
Closes #1993.
Closes https://github.com/CocoaPods/CocoaPods/issues/3870.
Closes https://github.com/CocoaPods/CocoaPods/issues/3992.

Too tired to finish this.

- Adds support for more configurable `Executable` usage (including `executable?`)
- Adds support for vendored dynamic frameworks
- Removes reliance on the network in the specs (except for the integration specs)
- Ensure `-ObjC` is added when there are static vendored frameworks

\c @steipete

### CODE REVIEW

**Comment by neonichu** [comment]
This looks good :+1:

We should think about adding an example with a vendored dynamic framework maybe?

File: lib/cocoapods/installer.rb [hunk 1]
```diff
@@ -392,8 +392,7 @@ def verify_no_static_framework_transitive_dependencies
           dependended_upon_targets = pod_targets.select { |t| dependencies.include?(t.pod_name) && !t.should_build? }
 
           static_libs = dependended_upon_targets.flat_map(&:file_accessors).flat_map do |fa|
-            static_frameworks = fa.vendored_frameworks.reject { |fw| `file #{fw + fw.basename('.framework')} 2>&1` =~ /dynamically linked/ }
-            fa.vendored_libraries + static_frameworks
+            fa.vendored_static_libraries + fa.vendored_static_frameworks
```
Comment (mrackwitz) [inline lib/cocoapods/installer.rb]: What about adding another accessor `FileAccessor#vendored_static_artifacts`, which does that?

Comment (segiddins) [inline lib/cocoapods/installer.rb]: I'd rather not add even more methods to `FileAccessor`

**Comment by greymouser** [comment]
I believe I just encountered an issue this PR resolves regarding why Reveal-iOS-SDK's Reveal.framework isn't copied over during build. If someone can direct me on how to install a version of cocoapods from a git repo, I'm quite happy to test, if that's helpful. (I'm just not very savvy with gem).

**Comment by segiddins** [comment]
@greymouser https://guides.cocoapods.org/using/unreleased-features.html

**Comment by jshier** [comment]
I'd like to test this as well, as it may fix #3847, but I'm getting compilation failure when building the json gem using the direction for building CocoaPods from source. 10.10.4, Xcode 7, 6.4, 6.3, and 6.2 all failed.

**Comment by segiddins** [comment]
Yeah, you need to monkey patch JSON 1.7.7 to get it to compile on ruby 2.2+

File: lib/cocoapods/executable.rb [hunk 2]
```diff
@@ -20,11 +20,15 @@ module Executable
...
+        Executable.execute_command(name, Array(command).flatten, false, :message => true)
       end
 
       define_method(name.to_s + '!') do |*command|
-        Executable.execute_command(name, Array(command).flatten, true)
+        Executable.execute_command(name, Array(command).flatten, true, :message => true)
+      end
+
+      define_method(name.to_s + '?') do |*command|
+        Executable.execute_command(name, Array(command).flatten, false)
```
Comment (segiddins) [inline lib/cocoapods/executable.rb]: should probably return `nil` if execution fails?

**Comment by domesticmouse** [comment]
This branch's pod executable breaks for Google Maps:
```
/Users/brettmorgan/github/swift-google-map/Pods/Target Support Files/Pods/Pods-frameworks.sh: line 13: syntax error near unexpected token `then'
```

The `Pods-frameworks.sh` file looks like this:
```
#!/bin/sh
set -e

echo "mkdir -p ${CONFIGURATION_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}"
mkdir -p "${CONFIGURATION_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}"

SWIFT_STDLIB_PATH="${DT_TOOLCHAIN_DIR}/usr/lib/swift/${PLATFORM_NAME}"

install_framework()
{
  if [ -r "${BUILT_PRODUCTS_DIR}/$1" ]; then
    local source="${BUILT_PRODUCTS_DIR}/$1"
  elsif [ -r "${BUILT_PRODUCTS_DIR}/$(basename "$1")" ]; then
    local source="${BUILT_PRODUCTS_DIR}/$(basename "$1")"
  elsif [ -r "$1" ]; then
    local source="$1"
  fi

  local destination="${CONFIGURATION_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}"

  if [ -L "${source}" ]; then
      echo "Symlinked..."
      source="$(readlink "${source}")"
  fi

  # use filter instead of exclude so missing patterns dont' throw errors
  echo "rsync -av --filter \"- CVS/\" --filter \"- .svn/\" --filter \"- .git/\" --filter \"- .hg/\" --filter \"- Headers\" --filter \"- PrivateHeaders\" --filter \"- Modules\" \"${source}\" \"${destination}\""
  rsync -av --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "${source}" "${destination}"

  local basename
  basename="$(basename "$1" | sed -E s/\\..+// && exit ${PIPESTATUS[0]})"
  binary="${destination}/${basename}.framework/${basename}"

  # Strip invalid architectures so "fat" simulator / device frameworks work on device
  if [[ "$(file "$binary")" == *"dynamically linked shared library"* ]]; then
    strip_invalid_archs "$binary"
  fi

  # Resign the code if required by the build settings to avoid unstable apps
  code_sign_if_enabled "${destination}/$(basename "$1")"

  # Embed linked Swift runtime libraries
  local swift_runtime_libs
  swift_runtime_libs=$(xcrun otool -LX "$binary" | grep --color=never @rpath/libswift | sed -E s/@rpath\\/\(.+dylib\).*/\\1/g | uniq -u  && exit ${PIPESTATUS[0]})
  for lib in $swift_runtime_libs; do
    echo "rsync -auv \"${SWIFT_STDLIB_PATH}/${lib}\" \"${destination}\""
    rsync -auv "${SWIFT_STDLIB_PATH}/${lib}" "${destination}"
    code_sign_if_enabled "${destination}/${lib}"
  done
}

# Signs a framework with the provided identity
code_sign_if_enabled() {
  if [ -n "${EXPANDED_CODE_SIGN_IDENTITY}" -a "${CODE_SIGNING_REQUIRED}" != "NO" -a "${CODE_SIGNING_ALLOWED}" != "NO" ]; then
    # Use the current code_sign_identitiy
    echo "Code Signing $1 with Identity ${EXPANDED_CODE_SIGN_IDENTITY_NAME}"
    echo "/usr/bin/codesign --force --sign ${EXPANDED_CODE_SIGN_IDENTITY} --preserve-metadata=identifier,entitlements \"$1\""
    /usr/bin/codesign --force --sign ${EXPANDED_CODE_SIGN_IDENTITY} --preserve-metadata=identifier,entitlements "$1"
  fi
}

# Strip invalid architectures
strip_invalid_archs() {
  binary="$1"
  # Get architectures for current file
  archs="$(lipo -info "$binary" | rev | cut -d ':' -f1 | rev)"
  stripped=""
  for arch in $archs; do
    if ! [[ "${VALID_ARCHS}" == *"$arch"* ]]; then
      # Strip non-valid architectures in-place
      lipo -remove "$arch" -output "$binary" "$binary" || exit 1
      stripped="$stripped $arch"
    fi
  done
  if [[ "$stripped" ]]; then
    echo "Stripped $binary of architectures:$stripped"
  fi
}
```

**Comment by segiddins** [comment]
Ah good catch @domesticmouse! I need to change that to `elif`

**Comment by domesticmouse** [comment]
With elsif -> elif this code works. 😎

Can you give me some idea on when this code should make it to production? 😀

**Comment by segiddins** [comment]
As soon as it gets finished up?

**Comment by mrackwitz** [comment]
There is one issue left: the embed frameworks phase isn't created for existing integrations. You would need to remove the `Pods.framework` first to trigger a re-integration. So either we add a migration path or we have to make the target integrator safer for such scenarios.

**Comment by segiddins** [comment]
@mrackwitz think I just addressed that :)

**Comment by mrackwitz** [comment]
:+1: 
I think, we will need to update the `install_add_pod` & `install_remove_pod` before states, because they are not supposed to test the migration path specifically. Perhaps we could use CLIntegracon's test inheriting for that and let them inherit the after state from the `install` spec.

**Comment by segiddins** [comment]
Sure, that makes sense! I'll try and get around to updating the integration specs tomorrow night, and adding new file accessor tests. I also probably will want to clean up the `Executable` changes, I don't really love this interface -- I'll probably move to take better advantage of named parameters

File: lib/cocoapods/installer/target_installer/aggregate_target_installer.rb [hunk 3]
```diff
@@ -145,10 +145,12 @@ def create_embed_frameworks_script
         frameworks_by_config = {}
         target.user_build_configurations.keys.each do |config|
           relevant_pod_targets = target.pod_targets.select do |pod_target|
-            pod_target.include_in_build_config?(target_definition, config) && pod_target.should_build?
+            pod_target.include_in_build_config?(target_definition, config)
           end
-          frameworks_by_config[config] = relevant_pod_targets.map do |pod_target|
-            "#{target_definition.label}/#{pod_target.product_name}"
+          frameworks_by_config[config] = relevant_pod_targets.flat_map do |pod_target|
+            frameworks = pod_target.file_accessors.flat_map(&:vendored_dynamic_frameworks).map { |fw| "${PODS_ROOT}/#{fw.relative_path_from(sandbox.root)}" }
```
Comment (segiddins) [inline lib/cocoapods/installer/target_installer/aggregate_target_installer.rb]: does this also need to handle `vendored_dynamic_libraries`?

Comment (mrackwitz) [inline lib/cocoapods/installer/target_installer/aggregate_target_installer.rb]: Yes, they have to be embedded as well.

Comment (segiddins) [inline lib/cocoapods/installer/target_installer/aggregate_target_installer.rb]: Can I simply add them the same way frameworks are added?

File: lib/cocoapods/generator/embed_frameworks_script.rb [hunk 4]
```diff
@@ -62,14 +64,21 @@ def script
             echo "rsync -av --filter \\"- CVS/\\" --filter \\"- .svn/\\" --filter \\"- .git/\\" --filter \\"- .hg/\\" --filter \\"- Headers\\" --filter \\"- PrivateHeaders\\" --filter \\"- Modules\\" \\"${source}\\" \\"${destination}\\""
             rsync -av --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "${source}" "${destination}"
 
+            local basename
+            basename="$(basename "$1" | sed -E s/\\\\..+// && exit ${PIPESTATUS[0]})"
+            binary="${destination}/${basename}.framework/${basename}"
```
Comment (mrackwitz) [inline lib/cocoapods/generator/embed_frameworks_script.rb]: This is specific to frameworks.

File: lib/cocoapods/generator/embed_frameworks_script.rb [hunk 5]
```diff
@@ -87,6 +96,24 @@ def script
             fi
           }
 
+          # Strip invalid architectures
+          strip_invalid_archs() {
```
Comment (mrackwitz) [inline lib/cocoapods/generator/embed_frameworks_script.rb]: Do we need to strip the swiftmodule as well?

File: lib/cocoapods/generator/embed_frameworks_script.rb (hunk 4 above)
Comment (mrackwitz) [inline lib/cocoapods/generator/embed_frameworks_script.rb]: Could be instead:
```shell
if echo "$1" | grep -qe ".*\.dylib$"; then
  binary="${basename}.dylib"
else
  local basename
  basename="$(basename "$1" | sed -E s/\\\\..+// && exit ${PIPESTATUS[0]})"
  binary="${destination}/${basename}.framework/${basename}"
fi
```

File: lib/cocoapods/installer/target_installer/aggregate_target_installer.rb (hunk 3 above)
Comment (mrackwitz) [inline lib/cocoapods/installer/target_installer/aggregate_target_installer.rb]: I think mostly. See my comment to the embed framework script generator.

File: lib/cocoapods/generator/embed_frameworks_script.rb (hunk 5 above)
Comment (segiddins) [inline lib/cocoapods/generator/embed_frameworks_script.rb]: Do the swiftmodules actually get used when copied? Fwiw, we don't do anything to the swiftmodules for RealmSwift.

File: lib/cocoapods/generator/embed_frameworks_script.rb (hunk 4 above)
Comment (segiddins) [inline lib/cocoapods/generator/embed_frameworks_script.rb]: yup! Just basically wrote a version of this

File: lib/cocoapods/generator/embed_frameworks_script.rb (hunk 5 above)
Comment (mrackwitz) [inline lib/cocoapods/generator/embed_frameworks_script.rb]: No, I think they are just used on link time. I didn't remembered that we filter them out on rsync already. :white_check_mark:

Comment (segiddins) [inline lib/cocoapods/generator/embed_frameworks_script.rb]: Yup, we do filter them in the rsync :)

File: lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb [hunk 6]
```diff
@@ -53,7 +53,7 @@ def save_as(path)
         #
         def generate
           includes_static_libs = !target.requires_frameworks?
-          includes_static_libs ||= pod_targets.flat_map(&:file_accessors).any? { |fa| !fa.vendored_libraries.empty? }
+          includes_static_libs ||= pod_targets.flat_map(&:file_accessors).any? { |fa| !fa.vendored_static_libraries.empty? || !fa.vendored_static_frameworks.empty? }
```
Comment (segiddins) [inline lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb]: `vendored_static_artifacts`

**Comment by segiddins** [comment]
This now handles setting `FRAMEWORK_SEARCH_PATHS` when a pod target depends upon a pod with vendored frameworks.

File: lib/cocoapods/installer/user_project_integrator/target_integrator.rb [hunk 7]
```diff
@@ -112,11 +112,30 @@ def update_to_cocoapods_0_34
         # @todo   This can be removed for CocoaPods 1.0
         #
         def update_to_cocoapods_0_37_1
-          (native_targets - native_targets_to_embed_in).any? do |native_target|
+          targets_to_embed = native_targets.select do |target|
```
Comment (segiddins) [inline lib/cocoapods/installer/user_project_integrator/target_integrator.rb]: @mrackwitz note that this fixes a bug with the migration, since `native_targets_to_embed_in` can be empty if targets are already integrated

File: lib/cocoapods/installer/analyzer.rb [hunk 8]
```diff
@@ -306,6 +306,7 @@ def generate_pod_targets(specs_by_target)
           # transitive dependencies can't be deduplicated.
           pod_targets.flat_map do |target|
             dependent_targets = transitive_dependencies_for_pod_target(target, pod_targets)
+            target.dependent_targets = dependent_targets
```
Comment (segiddins) [inline lib/cocoapods/installer/analyzer.rb]: this is recursive transitive dependencies, rather than shallow dependencies. Is this OK?

**Comment by neonichu** [comment]
LGTM

**Comment by segiddins** [comment]
Integration specs added/ updated. Will merge tomorrow, once I write up a changelog.

**Comment by segiddins** [comment]
Will merge if this passes

**Comment by mrackwitz** [comment]
What about my comment here:
>I think, we will need to update the `install_add_pod` & `install_remove_pod` before states, because they are not supposed to test the migration path specifically.

**Comment by segiddins** [comment]
Ah forgot about that :/ Will do that tonight

File: lib/cocoapods/installer/user_project_integrator/target_integrator.rb (hunk 7 above)
Comment (mrackwitz) [inline lib/cocoapods/installer/user_project_integrator/target_integrator.rb]: :+1:

**Comment by segiddins** [comment]
@mrackwitz not currently possible to use CLIntegracon's inheritance due to the issue I opened over there :/

**Comment by pronebird** [comment]
Is it possible to release -ObjC fix for frameworks as a part of minor patch release?

**Comment by neonichu** [comment]
@pronebird This change has been released already as part of 0.39.0

**Comment by pronebird** [comment]
@neonichu hmm... I am on 0.39.0 and still have the same issue.

**Comment by pronebird** [comment]
@neonichu you're right, I experience some side effects here... :)
