### PR TITLE
Fix missing -ObjC for xcframeworks - take 2

### LINKED ISSUE #10459: -ObjC is still not always generated when linking static xcframeworks
#10234 turns out to be an incomplete fix.

https://github.com/fthdgn/firebase-ios-sdk-issue-7595 demonstrates an example of a necessary `-ObjC` not being generated.  Full explanation https://github.com/firebase/firebase-ios-sdk/issues/7595#issuecomment-784731673.

Debugging shows the new builld_settings code added in #10234 only executed for aggregate targets and exiting early because of no response to `:vendored_xcframeworks`.

Unfortunately, I lost track of the test case I used with #10234 and I'm not sure what's different about the working and non-working cases.

### PR DESCRIPTION
**Pull request by paulb777**
Fix #10459 - a better file_accessor solution that undoes the build_settings.rb changes from #10234

Integration test companion is https://github.com/CocoaPods/cocoapods-integration-specs/pull/312

### CODE REVIEW

File: lib/cocoapods/sandbox/file_accessor.rb [hunk 1]
```diff
@@ -167,7 +167,7 @@ def vendored_frameworks
       #         that come shipped with the Pod.
       #
       def vendored_dynamic_frameworks
-        (vendored_frameworks - vendored_xcframeworks).select do |framework|
+        vendored_frameworks.select do |framework|
           Xcode::LinkageAnalyzer.dynamic_binary?(framework + framework.basename('.*'))
```
Comment (paulb777) [inline lib/cocoapods/sandbox/file_accessor.rb:171]: Need to update this to properly check if xcframework is dynamic

File: lib/cocoapods/sandbox/file_accessor.rb [hunk 2]
```diff
@@ -172,6 +172,17 @@ def vendored_dynamic_frameworks
         end
       end
 
+      # @return [Array<Pathname>] The paths of the dynamic xcframework bundles
+      #         that come shipped with the Pod.
+      #
+      def vendored_static_xcframeworks
+        vendored_xcframeworks.select do |path|
```
Comment (dnkoutso) [inline lib/cocoapods/sandbox/file_accessor.rb:179]: do these need to be `compact`?

Comment (dnkoutso) [reply lib/cocoapods/sandbox/file_accessor.rb:179]: I guess not it seems it only selects the ones that are static frameworks.

**Review by dnkoutso — APPROVED** [review]

**Review by amorde — APPROVED** [review]

File: lib/cocoapods/sandbox/file_accessor.rb (hunk 2 above)
Comment (paulb777) [reply lib/cocoapods/sandbox/file_accessor.rb:179]: Confirmed. Thanks @amorde !

**Comment by dnkoutso** [comment]
@paulb777 whats left here? is it just landing integration specs, merging this and publishing 1.10.2?

**Comment by paulb777** [comment]
@dnkoutso Yes. It should be ready to go.

**Comment by dnkoutso** [comment]
OK merged integration specs!

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by paulb777** [comment]
Integration tests updated in https://github.com/CocoaPods/cocoapods-integration-specs/pull/313
