### PR TITLE
Always codesign if target is codesigned, not just if required.

### LINKED ISSUE #3646: Pod frameworks are only codesigned if codesigning is required
After switching to `use_frameworks!`, my Mac app failed to run with the following error:

    /Users/nik/Library/Developer/Xcode/DerivedData/App-hjgvbxcrkfmoglbubiknvpwqfcvj/Build/Products/Debug/App.app: code object is not signed at all
    In subcomponent: /Users/nik/Library/Developer/Xcode/DerivedData/App-hjgvbxcrkfmoglbubiknvpwqfcvj/Build/Products/Debug/App.app/Contents/Frameworks/MASPreferences.framework
    Command /usr/bin/codesign failed with exit code 1

The framework is unsigned because the `Pods-App-frameworks.sh` script only codesignes it if `CODE_SIGNING_REQUIRED` is set (which I believe is only the case on iOS).

    Pods/Target Support Files/Pods-App/Pods-App-frameworks.sh:
    if [ "${CODE_SIGNING_REQUIRED}" == "YES" ]; then
        code_sign "${destination}/$1"
    fi

I think instead it should always sign if the target is being signed, e.g. like this:

    if [ -n "${EXPANDED_CODE_SIGN_IDENTITY}" ]; then
        code_sign "${destination}/$1"
    fi

### PR DESCRIPTION
**Pull request by nschum**
Fixes #3646

### CODE REVIEW

**Comment by segiddins** [comment]
@neonichu @mrackwitz please take a look at this?

**Comment by segiddins** [comment]
ping @neonichu ?

**Comment by neonichu** [comment]
@nschum Do you have a shareable repro case for the original issue by any chance?

**Comment by nschum** [comment]
I created one: https://www.dropbox.com/s/m8vvcj8buuy7arr/SigningTest.zip?dl=0

##### Manual steps

1. Create a "Cocoa Application" OS X project in Xcode.
2. Add Podfile:

    inhibit_all_warnings!
    use_frameworks!
    platform :osx, "10.10"
    pod 'MASPreferences'

3. Run `pod install`
4. In Build Settings, enable code signing by setting "Code Signing Identity" to "Mac Developer".

**Comment by neonichu** [comment]
@nschum Thanks for the example! However, even with your patch applied, it fails for me, with the same error message as described in #3646:

```
/Users/boris/Library/Developer/Xcode/DerivedData/SigningTest-gppafqqunbsmckbecrgqraujscsd/Build/Products/Debug/SigningTest.app: code object is not signed at all
In subcomponent: /Users/boris/Library/Developer/Xcode/DerivedData/SigningTest-gppafqqunbsmckbecrgqraujscsd/Build/Products/Debug/SigningTest.app/Contents/Frameworks/MASPreferences.framework
Command /usr/bin/codesign failed with exit code 1
```

**Comment by neonichu** [comment]
@nschum Ah, sorry, I see my problem now, the patch didn't apply cleanly, now it works great! Could you please rebase it, then I'll merge :+1:

**Comment by nschum** [comment]
That was yesterday. :(

Looks like #3550 breaks codesigning altogether, even for iOS apps. (The paths are wrong.)
I'll see if I can fix both together.

**Comment by nschum** [comment]
Test case for iOS signing broken on master: https://www.dropbox.com/s/qf2cmcvo9ltyvud/SigningTest2.zip?dl=0
(when building for device)

File: lib/cocoapods/generator/embed_frameworks_script.rb [hunk 1]
```diff
@@ -56,10 +56,9 @@ def script
             # use filter instead of exclude so missing patterns dont' throw errors
             echo "rsync -av --filter \"- CVS/\" --filter \"- .svn/\" --filter \"- .git/\" --filter \"- .hg/\" --filter \"- Headers\" --filter \"- PrivateHeaders\" --filter \"- Modules\" ${source} ${destination}"
             rsync -av --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "${source}" "${destination}"
+
             # Resign the code if required by the build settings to avoid unstable apps
-            if [ "${CODE_SIGNING_REQUIRED}" == "YES" ]; then
-                code_sign "${destination}/$1"
-            fi
+            code_sign_if_enabled "${destination}/$(basename $1)"
```
Comment (segiddins) [inline lib/cocoapods/generator/embed_frameworks_script.rb]: should this be `"${destination}/$(base name \\"$1\\").framework" ?

Comment (nschum) [inline lib/cocoapods/generator/embed_frameworks_script.rb]: You're right about quoting, in case the framework contains spaces (though the syntax is `"$(basename "$1")"`). I'll fix it.

`basename` doesn't strip the extension unless you tell it to, though. So that parts fine.
