### PR TITLE
Fix a regression in static library header dir paths

### LINKED ISSUE #8836: Header path changed in 1.7.0
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install` and built my project with Xcode. That project does work properly when using CocoaPods 1.6.1.

## What did you expect to happen?

My project to build properly when using CocoaPods 1.7.0.

## What happened instead?

Xcode complained it could not find headers with a hyphen `-` in the pod name.

Looking at files in the `Pods/` directory, it seems pod names in `Pods/Headers/Public/` and `Pods/Headers/Private/` now have hyphens `-` replaced by underscores `_` (though they still use hyphens in `Pods/`).

I had to change for example:
```objc
#import <pantryman-ios/pantryman-ios.h>
```
to: (changing the hyphen in the directory name to an underscore, but keeping the hyphen in the file name)
```objc
#import <pantryman_ios/pantryman-ios.h>
```
for my project to continue building.

That is a breaking change that doesn't seem to be mentioned in the change log. Was that intended?

### Stack

```
   CocoaPods : 1.7.0
        Ruby : ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.21.0
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

The project's Podfile doesn't `use_frameworks!`.

### PR DESCRIPTION
**Pull request by amorde**
Closes #8836

Original implementation in #8706 was a bit heavy handed - we can get the same bug fix by adjusting the behavior of the sandbox cleaner.

### CODE REVIEW

**Comment by dnkoutso** [comment]
@amorde this ensures both https://github.com/CocoaPods/CocoaPods/issues/8836 and work https://github.com/CocoaPods/CocoaPods/issues/8695?

File: spec/unit/installer/sandbox_dir_cleaner_spec.rb [hunk 1]
```diff
@@ -32,15 +36,25 @@ module Pod
...
       FileUtils.mkdir_p(banana_lib_public_headers)
       FileUtils.mkdir_p(banana_lib_private_headers)
+      FileUtils.mkdir_p(coconut_lib_public_headers)
+      FileUtils.mkdir_p(coconut_lib_private_headers)
       @cleaner.expects(:remove_dir).with(random_pod_private_headers)
       @cleaner.expects(:remove_dir).with(random_pod_public_headers)
+      @cleaner.expects(:remove_dir).with(coconut_lib_public_headers).never
+      @cleaner.expects(:remove_dir).with(coconut_lib_private_headers)
       @cleaner.clean!
-      banana_lib_public_headers.should.exist?
```
Comment (dnkoutso) [inline spec/unit/installer/sandbox_dir_cleaner_spec.rb]: what about these assertions?

**Comment by amorde** [comment]
Have tested against #8695 but not #8836 yet, will do that before merging

File: spec/unit/installer/sandbox_dir_cleaner_spec.rb (hunk 1 above)
Comment (amorde) [reply spec/unit/installer/sandbox_dir_cleaner_spec.rb]: since `:remove_dir` is stubbed above, these assertions will always pass. they aren't testing anything

**Comment by amorde** [comment]
Confirmed #8836 is fixed with this PR
