### PR TITLE
Remove bogus PROVISIONING_PROFILE_SPECIFIER value from Pods project

### LINKED ISSUE #7038: Dummy provisioning profile "NO_SIGNING/" causing build issues for us
Our command line builds in Xcode 9 have started to fail due to CocoaPods inserting a dummy value of "NO_SIGNING/" into the Provisioning Profile build settings of the Pods project.

Is there some reason the dummy value is required? Our builds work if we delete this dummy value.

### PR DESCRIPTION
**Pull request by Ruenzuo**
It's a bit tough to prepare an example project for this, as you need a project with valid code signing settings to reproduce this, but I'm happy to send one if you need it.

CocoaPods 1.3.1 sets the value of `PROVISIONING_PROFILE_SPECIFIER` to `NO_SIGNING/` which breaks the archiving action on Xcode 9 (but also believe it happens in the latest versions of Xcode 8, as some users reported below) using CODE_SIGN_IDENTITY environment variable.

This is how my build settings look like, automatic code signing is disabled.

```
//Config.release.xcconfig
#include "Pods/Target Support Files/Pods-Piggy/Pods-Piggy.release.xcconfig"

DEVELOPMENT_TEAM = TEAM_ID
PRODUCT_BUNDLE_IDENTIFIER = com.company.app
PROVISIONING_PROFILE_SPECIFIER = My Provisioning profile
```

Some logs running the following command:

```bash
xcodebuild -workspace Piggy.xcworkspace/ -scheme Piggy -configuration Release -destination 'generic/platform=iOS' -archivePath './archive' archive CODE_SIGN_IDENTITY="iPhone Distribution: COMPANY_NAME (TEAM_ID)"
```

```
User defaults from command line:
    IDEArchivePathOverride = /Users/crisosto/Downloads/Piggy/archive

Build settings from command line:
    CODE_SIGN_IDENTITY = iPhone Distribution: COMPANY_NAME (TEAM_ID)

=== BUILD TARGET AFNetworking OF PROJECT Pods WITH CONFIGURATION Release ===

Check dependencies
Code Signing Error: AFNetworking does not support provisioning profiles. AFNetworking does not support provisioning profiles, but provisioning profile NO_SIGNING/ has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.

** ARCHIVE FAILED **
```

But if you use build setting value in your project instead of the environment variable, like:

```
xcodebuild -workspace Piggy.xcworkspace/ -scheme Piggy -configuration Release -destination 'generic/platform=iOS' -archivePath './archive' archive
```
```
//Config.release.xcconfig
#include "Pods/Target Support Files/Pods-Piggy/Pods-Piggy.release.xcconfig"

...
CODE_SIGN_IDENTITY = iPhone Distribution: COMPANY_NAME (TEAM_ID)
...
```

Everything works as expected.

Removing the bogus value from the Pods project also solves the issue, like some users already noticed. ([#1](https://github.com/CocoaPods/CocoaPods/pull/5528#issuecomment-316735830), [#2](https://github.com/realm-demos/realm-tasks/commit/d0da07a87b1324af58adae7cd2324c75fd0f0a6b))

I guess you could ignore this PR if there's a valid reason to set that bogus value in the Pods project, as there are plenty of workarounds for this and so far and I've been only able to reproduce it if I try to override `CODE_SIGN_IDENTITY` with environment variables.

Closes #7038

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Remove bogus PROVISIONING_PROFILE_SPECIFIER value from Pods project  
  [Ruenzuo](https://github.com/Ruenzuo)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by dnkoutso** [comment]
Needs a changelog entry. Not sure if this will break a lot of other stuff though so anyone who has thoughts should review this.

**Comment by DanToml** [comment]
This would break a lot of builds outside of the command line I think. - A better approach might be overriding the provisioning profile specifier on the command line too.

**Comment by piotr-tobolski** [comment]
I used this code in the Podfile as a workaround:
```
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
    end
end
```

Similar thing was done to fix realm-demos/realm-tasks#415 It does almost the same thing as this PR.

If is breaks something for anyone who uses it please describe your problem here (and solution if you have one). It will be very useful for fixing this issue.

**Comment by icecrystal23** [comment]
This fixes #7038

**Comment by dnkoutso** [comment]
We do not know yet if this will merge and might have to do Xcode versioning check here in order to prevent all others from breaking from this change.

**Comment by icecrystal23** [comment]
Do you know for sure that this will break anything? Our Xcode 8 builds continued to work after we manually removed the "NO_SIGNING/" value from the Pods project.

**Comment by HofiOne** [comment]
found the same issue on Xcode 9 final

as a workaround we are using

    post_install do |installer|
        installer.pods_project.build_configurations.each do |config|
            config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
        end
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
            end
        end
    end


in the post install step in the podfile

**Comment by Buju77** [comment]
CP 1.3.1 also broke our archiving builds. Using above mentioned workaround post install hooks works fine.

**Comment by derpixeldan** [comment]
Any updates on this? It's been a while since Xcode 9 is out and `NO_SIGNING/` keeps breaking `xcodebuild` archiving.

**Comment by meiravf** [comment]
Is there going to be a solution for this issue? Changing the pods projects and removing the `NO_SIGNING/` value is not a valid option for us.

**Comment by alaeddineG** [comment]
Hi,

The following :
```
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
    end
end
```

is not helping me. :(
I tried this and it's the some thing :

```
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
    end
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
        end
    end
end
```

This is what the command I use to archive :

`xcodebuild -sdk iphoneos11.1 -configuration SomeConfig -workspace MyApp.xcworkspace -scheme MyApp archive PROVISIONING_PROFILE_SPECIFIER=some-prov-profile-uuid -archivePath Myapp.xcarchive CODE_SIGN_IDENTITY=SomeSigningIdentityHash`

And I have the same ** ARCHIVE FAILED ** issue example 👍 

```
Check dependencies
Code Signing Error: GTMSessionFetcher does not support provisioning profiles. GTMSessionFetcher does not support provisioning profiles, but provisioning profile what-ever-provision-profile-uuid has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.

** ARCHIVE FAILED **


The following build commands failed:
	Check dependencies
	Check dependencies
	Check dependencies
	Check dependencies
	Check dependencies
	Check dependencies
	Check dependencies

```

The previous comment is working well with xcode 8.x  (SDK iphoneos10.2)only happening with xcode 9.x (0 & 1)

For now our build server is stuck with building on iphoneos10.2 until this get solved.

Any help please ?

**Comment by piotr-tobolski** [comment]
@alaeddineG you are setting the provisioning profile through command line in this place: `PROVISIONING_PROFILE_SPECIFIER=some-prov-profile-uuid`. It is set for the whole project. Xcode 9 requires having no profile set for cocoapods. What I suggest you to do is to write ruby script using xcodeproj gem for setting desired selected profiles for selected targets. It will allow you higher flexibility and you will be able to overcome this issue. This is what I do currently.

**Comment by alaeddineG** [comment]
@piotr-tobolski Thank you for the tips. I think it make sense.
But can you please give me an example ? I would really appreciate.

**Comment by kapfab** [comment]
Does someone know if/why we need to set this invalid PP specifier ? @neonichu, could you help there?
And if it is definitely necessary to prevent signing, couldn't we use `build_configuration.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'` instead of `build_configuration.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'` and remove this bogus this `PROVISIONING_PROFILE_SPECIFIER`?

**Comment by kapfab** [comment]
This PR has been there for months and is still stuck, waiting for someone (but who?) to decide whether Cocoapods can be used by real organizations with continuous integration platforms…
The workaround works, but having to add custom temporary code to Podfiles (or Fastfiles) in all active branches of all our apps is just insane.
Is this a sign of Cocoapods's quiet death ?

**Comment by orta** [comment]
Multiple members of the core team have commented on this thread with ideas that don't look like they've either been discussed or implemented 

https://github.com/CocoaPods/CocoaPods/pull/6964#issuecomment-324187816 and CI is red

Remember that people maintain this project used in millions of apps in their spare time. You can be snarky about people's time allocations, or you can contribute time and effort to help get this unblocked like @Ruenzuo has tried.

**Comment by dnkoutso** [comment]
We've also been running CocoaPods 1.4.x internally and archiving continues to work. This seems contradicting to what other comments and the original PR here say.

Changes like these should not be merged in haste and without proper due diligence as it could break a ton of other cases the other way around.

This seems to be the reality of the difficulty and complexity of the iOS build and compilation.

**Comment by kapfab** [comment]
I am not snarky at all. You might not share my worries, but that this long-running issue is clearly playing against Cocoapods as a viable solution for some big companies.
I am thankful to @Ruenzuo and that’s why I regret his PR is blocked. I would not be there commenting if I wasn’t willing to help.
If you had a look at my previous post, you would have seen I suggested a potential solution that might fix the issue for both manual and automated builds (but I need to know why this has been done this way, I do not want with a PR blocked in the same way or breaking specific Pods).

**Comment by dnkoutso** [comment]
Can someone provide a quick sample app demonstrating the issue? I will do a bit of investigation myself.

**Comment by icecrystal23** [comment]
It looks like the failed CI build is related to the change not being taken into account in some test validation input.  Seems like simply updating the test validation would make the build succeed.

**Comment by kapfab** [comment]
@dnkoutso, are you using Xcode 9?
All Xcode 9 projects with Pods I've seen lately built from command line (via Fastlane, in our case) are failing because of this `NO_SIGNING/` specifier.

**Comment by fangmobile** [comment]
I ran into this and the workaround does not work for me since I set PROVISIONING_PROFILE_SPECIFIER on command line on my Jenkins job.
I will try what @piotr-tobolski suggested. 
If some one has more detailed info about his solution, please share it. 
Thanks.

**Comment by dnkoutso** [comment]
This needs a rebase now that 1.4.0 shipped and we are considering merging this. If I do not hear back I will make a PR myself.

File: lib/cocoapods/installer/xcode/pods_project_generator.rb [hunk 1]
```diff
@@ -151,7 +151,6 @@ def prepare
               build_configuration.build_settings['STRIP_INSTALLED_PRODUCT'] = 'NO'
               build_configuration.build_settings['CLANG_ENABLE_OBJC_ARC'] = 'YES'
               build_configuration.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
-              build_configuration.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = 'NO_SIGNING/' # a bogus provisioning profile ID assumed to be invalid
```
Comment (segiddins) [inline lib/cocoapods/installer/xcode/pods_project_generator.rb]: i think we might also want to set `CODE_SIGNING_ALLOWED = NO` ?

Comment (icecrystal23) [reply lib/cocoapods/installer/xcode/pods_project_generator.rb]: That's a reasonable proposal IMO, but please consider doing that outside of this PR.  A lot of folks are waiting for this and I'd rather not drag it on with additional discussions about other fields.

Comment (segiddins) [reply lib/cocoapods/installer/xcode/pods_project_generator.rb]: After talking with some folks, I'm almost certain that setting _needs_ to be set in order to have Xcode not try to code sign at all, which is why we added the bogus provisioning profile in the first place.

**Comment by Ruenzuo** [comment]
@dnkoutso Sorry I don’t think I’ll find the time to update this before the weekend. I need to check if `CODE_SIGNING_ALLOWED = NO` doesn’t break the reproducible case I have and I also have to update the integration specs. Feel free to close this PR if you want to get it done yourself faster.

File: lib/cocoapods/installer/xcode/pods_project_generator.rb (hunk 1 above)
Comment (icecrystal23) [reply lib/cocoapods/installer/xcode/pods_project_generator.rb]: If that were the case then people's workarounds wouldn't be working (clearing just the provisioning profile specifier).

**Comment by dhoskins** [comment]
The problem arises in my experience when `PROVISIONING_PROFILE` is set on the archive command as was by @alaeddineG.

I worked round this issue by setting a different variable, e.g. `ARCHIVE_PROVISIONING_PROFILE`. Then in Xcode project > Build Settings > Signing set Provisioning Profile to `$ARCHIVE_PROVISIONING_PROFILE`.

**Comment by chrisknepper** [comment]
I'd just like to chime in here that for projects which commit their Pods, the `post_install` hook workaround doesn't seem to work because that hook wouldn't run on build. The project I'm working on with Xcode 9 uses manual signing **and** we commit our Pods.

We build via `xcodebuild` and passing `PROVISIONING_PROFILE_SPECIFIER=xxxx`, which seems to override the value of that key (`NO_SIGNING/`) which was specified in our **Pods.xcodeproj/project.pbxproj**.

To get a successful build, we set the following config keys/values in our Pods.xcodeproj/project.pbxproj for each target/build configuration:

```
CODE_SIGNING_ALLOWED = NO;
CODE_SIGNING_REQUIRED = NO;
PROVISIONING_PROFILE = '';
PROVISIONING_PROFILE_SPECIFIER = '';
```

I understand that some of those options may be deprecated or redundant, but I'm not an iOS dev by trade and setting those worked for us. I have also referenced this issue on StackOverflow because this seems to affect iOS projects with embedded libraries/projects due to the significant changes Apple made in regard to code signing in Xcode 9.

**Comment by piotr-tobolski** [comment]
@chrisknepper It works great for projects that commit their Pods, you just have to run "pod install" after adding this hook (before commiting the changes). Code in Podfile is executed only during the integration and since the pods are commited then any change in Podfile requires running the integration before commiting.

**Comment by vonovak** [comment]
For me this didn't work:

```
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
    end
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
        end
    end
end
```
More specifically, it did remove the dummy NO_SIGNING profile but then I got another error like: `Code Signing Error: GTMSessionFetcher does not support provisioning profiles. GTMSessionFetcher does not support provisioning profiles, but provisioning profile **the UUID provided by build script** has been manually specified. ...` So it just moved the problem somewhere else.

However, being more explicit about not using code signing made it work:

```
  installer.pods_project.build_configurations.each do |config|
            config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
            config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
        end
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
                config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
                config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
            end
        end
```

Interestingly enough, this also works for me, so the `PROVISIONING_PROFILE_SPECIFIER` doesn't have to necessarily be removed for me.

```
  installer.pods_project.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
            config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
        end
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
                config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
            end
        end
```

**Comment by piotr-tobolski** [comment]
Setting the build options for targets shouldn't be needed as they don't override project's value (at least in my case). Interesting thing is that I have `CODE_SIGNING_REQUIRED` already set to `NO` without adding any scripts.

**Comment by jcarroll-mediafly** [comment]
Having this issue on our CI server. Oddly enough, local builds are fine. Same xcode version, same cocoapods, etc...

**Comment by jsaha2007** [comment]
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
    end
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
        end
    end
end

Its not working for me. I am facing same issue still now

"error: exportArchive: Alamofire.framework does not support provisioning profiles."

Can anyone please help me, I am stuck for more than 3 days.

I am reinstalling the pods after doing that from local and commiting it.is it enough, or I need to do something else also.

Please help me.

**Comment by amorde** [comment]
@jsaha2007 could you try the latest beta (with `sudo gem install cocoapods --pre`) and see if that resolves the issue for you? Please try the beta _without_ the `post_install` workaround. Thanks!

**Comment by jsaha2007** [comment]
@amorde thanks for the answer, but I am having the same issue.

**Comment by amorde** [comment]
Okay, there might be a different bug then. Could you open another issue with a sample project that reproduces the bug?

**Comment by jsaha2007** [comment]
sure @amorde I will do that.
