### PR TITLE
Resolved an issue that could cause spec repo updates to fail on CI servers

### LINKED ISSUE #7317: Multiple "pod repo update" commands fail because of git.
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Multiple jenkins jobs on the same machine ran `pod repo update`, this obviously fails because git holds locks: 

```bash
Exit status of command 'pod repo update ios-my-cocoapods' was 1 instead of 0.
Updating spec repo `ios-my-cocoapods`
  $ /usr/local/bin/git -C /Users/builduser/.cocoapods/repos/ios-my-cocoapods fetch origin --progress
  $ /usr/local/bin/git -C /Users/builduser/.cocoapods/repos/ios-my-cocoapods rev-parse --abbrev-ref HEAD
  master
  $ /usr/local/bin/git -C /Users/builduser/.cocoapods/repos/ios-my-cocoapods reset --hard origin/master
  fatal: Unable to create '/Users/builduser/.cocoapods/repos/ios-my-cocoapods/.git/index.lock': File exists.
  
  Another git process seems to be running in this repository, e.g.
  an editor opened by 'git commit'. Please make sure all processes
  are terminated then try again. If it still fails, a git process
  may have crashed in this repository earlier:
  remove the file manually to continue.
[!] CocoaPods was not able to update the `ios-my-cocoapods` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`
```

## What did you expect to happen?

Given that cocoapods is often used in CI jobs, I'd expect cocoapods to be able to handle this case. 

## What happened instead?

See error message above.

## CocoaPods Environment

```
$ pod env

### Stack

```
   CocoaPods : 1.4.0.beta.1
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
    RubyGems : 2.7.3
        Host : Mac OS X 10.13.2 (17C88)
       Xcode : 9.2 (9C40b)
         Git : git version 2.15.0
Ruby lib dir : /usr/local/Cellar/ruby/2.4.2_1/lib
Repositories : ios-my-cocoapods - git@github.privatecompanyurl.com:ios/ios-my-cocoapods.git @ 03be05fe4339a34927f41c5e6e6c592436d276ca
               master - https://github.com/CocoaPods/Specs.git @ 77a078acf65b13224ab92950ae06191e0a73ffb6
```

### Installation Source

```
Executable Path: /Users/dbeard/.podenv/versions/1.4.0.beta.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### PR DESCRIPTION
**Pull request by rpecka**
🌈
Resolves #7317 
There is an issue when running CI servers that build more than one instance of a project at a time where if two `pod repo update` commands are issued in quick succession, the build will fail because the updates are attempting to simultaneously modify the git repositories.

To solve this problem, I've added logic to create a `Spec_Lock` file in the spec repo directory and then lock that file until the git updates are complete. This causes successive repo commands to execute one at a time.

This is my time using ruby and contributing to CocoaPods so please let me know if there are best practices I missed or any other issues. In particular, I'm not sure that I wrote the unit test correctly however, I did test it with and without my changes and it worked properly.

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Resolved an issue that could cause spec repo updates to fail on CI servers  
  [rpecka](https://github.com/rpecka)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

File: lib/cocoapods/sources_manager.rb [hunk 1]
```diff
@@ -88,13 +88,18 @@ def update(source_name = nil, show_output = false)
         end
 
         changed_spec_paths = {}
+        # Ceate the Spec_Lock file if needed and lock it so that concurrent
+        # repo updates do not cause each other to fail
+        f = File.open("#{Config.instance.repos_dir}/Spec_Lock", File::CREAT)
```
Comment (segiddins) [inline lib/cocoapods/sources_manager.rb]: can we use the block form of `File.open`, since this will leak file handles if an exception occurs?

File: lib/cocoapods/sources_manager.rb [hunk 2]
```diff
@@ -88,13 +88,18 @@ def update(source_name = nil, show_output = false)
...
+        f.flock(File::LOCK_EX)
```
Comment (segiddins) [inline lib/cocoapods/sources_manager.rb]: do we need to also unlock the file?

File: spec/functional/command/repo/update_spec.rb [hunk 3]
```diff
@@ -47,5 +47,21 @@ module Pod
       run_command('repo', 'update', 'repo2')
       (repo2 + 'README').read.should.include 'Updated'
     end
+
+    it 'repo updates do not fail when executed in parallel' do
+      repo1 = repo_make('repo1')
+      repo_clone('repo1', 'repo2')
+      repo_make_readme_change(repo1, 'Updated')
+      Dir.chdir(repo1) { `git commit -a -m "Update"` }
```
Comment (segiddins) [inline spec/functional/command/repo/update_spec.rb]: `Pod::Executable.capture_command!('git', %w(commit -a -m Update))` ?

File: lib/cocoapods/sources_manager.rb (hunk 2 above)
Comment (rpecka) [reply lib/cocoapods/sources_manager.rb]: The file should be unlocked once it gets closed, right?

File: spec/functional/command/repo/update_spec.rb (hunk 3 above)
Comment (rpecka) [reply spec/functional/command/repo/update_spec.rb]: I put this inside of the `chdir`, is that what you wanted? Why is this needed?

File: lib/cocoapods/sources_manager.rb (hunk 2 above)
Comment (segiddins) [reply lib/cocoapods/sources_manager.rb]: I',m not sure!

File: spec/functional/command/repo/update_spec.rb (hunk 3 above)
Comment (segiddins) [reply spec/functional/command/repo/update_spec.rb]: It's better to avoid using the shell whenever possible

File: lib/cocoapods/sources_manager.rb (hunk 2 above)
Comment (rpecka) [reply lib/cocoapods/sources_manager.rb]: The tests wouldn’t be passing if closing didn’t unlock the file so we’re good

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

File: lib/cocoapods/sources_manager.rb [hunk 4]
```diff
@@ -88,11 +88,16 @@ def update(source_name = nil, show_output = false)
...
         changed_spec_paths = {}
-        sources.each do |source|
-          UI.section "Updating spec repo `#{source.name}`" do
-            changed_source_paths = source.update(show_output)
-            changed_spec_paths[source] = changed_source_paths if changed_source_paths.count > 0
-            source.verify_compatibility!
+        # Ceate the Spec_Lock file if needed and lock it so that concurrent
+        # repo updates do not cause each other to fail
+        File.open("#{Config.instance.repos_dir}/Spec_Lock", File::CREAT) do |f|
+          f.flock(File::LOCK_EX)
```
Comment (Whirlwind) [inline lib/cocoapods/sources_manager.rb]: Will it lock all repo sources? If I have 10 spec repos, other CI task will wait all repo update finish, right?

Could we only lock the single repo to allow another CI task update other spec repos?

Comment (rpecka) [reply lib/cocoapods/sources_manager.rb]: I could change it to a per-repo lock file like ‘Spec_Lock-master’ and ‘Spec_Lock-myrepo’. Is that what you’re suggesting?

Comment (Whirlwind) [reply lib/cocoapods/sources_manager.rb]: yeah. Why not write the lock file in per-repo directory instead of `Spec_Lock-master` in the root directory?

Comment (rpecka) [reply lib/cocoapods/sources_manager.rb]: I think we should probably avoid getting those repos dirty

Comment (Whirlwind) [reply lib/cocoapods/sources_manager.rb]: we could ignore the file in the .git/exclude/info

Comment (rpecka) [reply lib/cocoapods/sources_manager.rb]: I found `.git/info/exclude` is that what you mean? If so, what does that do?

**Comment by dnkoutso** [comment]
@rpecka can you rebase/squash to also take care of the conflict.

**Comment by rpecka** [comment]
> @rpecka can you rebase/squash to also take care of the conflict.

I got rid of the conflict. Is squashing optional?

File: CHANGELOG.md [hunk 5]
```diff
@@ -72,6 +72,9 @@ To install release candidates run `[sudo] gem install cocoapods --pre`
 * Do not link specs into user targets that are only used by app specs.  
   [Samuel Giddins](https://github.com/segiddins)
 
+* Resolved an issue that could cause spec repo updates to fail on CI servers.
```
Comment (dnkoutso) [inline CHANGELOG.md]: this is in the wrong spot.

**Comment by dnkoutso** [comment]
The changelog entry is in the wrong spot otherwise we can merge this.

**Comment by fandor92** [comment]
It's still happening with the same error on our CI system using GitLab and CocoaPods 1.7.5 :(
