### PR TITLE
Fixed pod repo push validation and push issues related to Dir.chdir

### LINKED ISSUE #5805: 'pod spec lint' fails with message 'App.xcworkspace' does not exist. 🌈
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Run 'pod spec lint --verbose' on 'https://github.com/psturm-swift/SwiftySignals/blob/Swift_3.0/SwiftySignals.podspec'

## What did you expect to happen?
I expect that the validation passes.

## What happened instead?
Validation ends with an error saying that App.xcworkspace does not exist. However, if I run pod spec lint with option --no-clean the workspace is there but it is not found by pod spec lint.

### Stack

```
   CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8S201h)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/psturm/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 34ac2d09edb2bf66b9cb6badcccdc32c99fd1192
```

### Installation Source

```
Executable Path: /Users/psturm/.rvm/rubies/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
https://github.com/psturm-swift/SwiftySignals/tree/Swift_3.0

### PR DESCRIPTION
**Pull request by benasher44**
Removes uses of `Dir.chdir` for this flow. It prefers using `git -C` and passing the full path to App.xcworkspace for validation. This fixes #5805

### CODE REVIEW

**Comment by benasher44** [comment]
Unsure where in ruby I should be quoting and not-quoting arguments for shell commands. Maybe someone could provide some guidance there?

File: lib/cocoapods/command/repo/push.rb [hunk 1]
```diff
@@ -145,7 +145,7 @@ def validate_podspec_files
         # @return [void]
         #
         def check_repo_status
-          clean = Dir.chdir(repo_dir) { `git status --porcelain  2>&1` } == ''
+          clean = `git -C #{repo_dir} status --porcelain  2>&1` == ''
```
Comment (orta) [inline lib/cocoapods/command/repo/push.rb]: these should need the quotations around the ` #{repo_dir}` -> ` "#{repo_dir}"`

**Comment by benasher44** [comment]
One thing to note is that because of all of the `Dir.chdir` going on in tests, the tests aren't doing so well in an Xcode 8 environment at least for me. I can fix all of the `git` calls to use `git -C`, but that's not enough. There are many instances where it needs to `Dir.chdir` to run a working directory-dependent `pod` command.

**Comment by segiddins** [comment]
@benasher44 all the stuff using `Executable` doesn't even use a shell at all, so no need to quote anything

**Comment by benasher44** [comment]
@segiddins 👍. But I still need to use quotes for paths in back tick strings, so that it correctly handles paths with spaces, correct?

**Comment by segiddins** [comment]
@benasher44 yup

**Comment by benasher44** [comment]
Great. I think we're set there then. Any thoughts on the other `Dir.chdir` issue I mentioned? I'm basically holding out dumping Xcode 7 so that I can run `bundle exec rake` 😭. I can continue down the `git -C` path (bad pun) and convert more `git` commands, but this doesn't fix places where we have to `Dir.chdir` to run a `pod` command in tests.

**Comment by segiddins** [comment]
@benasher44 given that the issue is now fixed in Xcodeproj, it shouldn't be necessary to?

**Comment by benasher44** [comment]
Many `Dir.chdir`s seem to still be affected in the main CocoaPods project. Did we expect the patch in Xcodeproj to apply here as well? If so, that doesn't seem to be the case.

**Comment by segiddins** [comment]
Did anyone actually `bundle update xcodeproj`?

**Comment by DanToml** [comment]
@benasher44 when running CocoaPods specs against Xcodeproj head, they all pass for me. (including validation)

**Comment by benasher44** [comment]
@DanToml huh interesting. I ran into this bug yesterday when using 1.1.0.beta.2 at work. I can double check, but then I was debugging I switched to CocoaPods master and was hitting it there too.

If I run just `bundle exec bacon spec/unit/validator_spec.rb` on the 1.1.0.beta.2 tag, one spec fails in Core's `ensure_in_repo!`. After running that whole spec, `git status` tells me I'm now in the CocoaPods specs repo.

**Comment by benasher44** [comment]
I think it's important to do what with `xcodebuild` version 8 selected (by `sudo xcode-select --switch`ing to the right Xcode if you have 2 installed)

**Comment by benasher44** [comment]
@DanToml After `bundle update xcodeproj`, the spec does pass without the changes in this PR. That said, `git -C` seems like a better alternative to `Dir.chdir`: saves a `Dir.chdir` (slow now but that could change) and `git -C` will error instead of do git ops on the wrong repo.

For the `xcodebuild` change, it seems like a minor improvement to pass the full path to the workspace since it will accept one.

In any case, these are now both just improvements, so they're probably not release blocking.

**Comment by benasher44** [comment]
These tests should pass once this PR is updated to use the changes from CocoaPods/Core#352, since it's expecting more `git -C` from that change.

**Comment by DanToml** [comment]
@benasher44 Yeah the Xcodeproj change was only merged yesterday so didn't go into b2. 

This is definitely just a nice to have now, so it's your call but I'd personally like this to go in the 1.1 release candidate (otherwise we can hold off till 1.2).

**Comment by benasher44** [comment]
@DanToml I'm comfortable with this change in the RC 👍. Once the Core change is shipped, I'll update this one.

**Comment by DanToml** [comment]
@benasher44 👍 SGTM.

**Comment by benasher44** [comment]
This doesn't fully fix anything without either the `bundle update xcodeproj` bump or bumping the version of CP and therefore Core. Once Core is updated, there are validator specs that will need to be fixed. I'll revert the changes here that depend on the Core update, and then I think this is ready to go.

**Comment by benasher44** [comment]
Still one failure in here that looks real. Working on that.

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! 
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Fixed pod repo push validation and push issues related to Dir.chdir 
  [benasher44](https://github.com/benasher44)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by heshamsalman** [comment]
Heads up, this works to fix issues related to App.xcworkspace not being found, but in my testing it doesn't seem to fix the issue of the generated app target not having the proper swift version. 

Managed to hack together a situation-specific fix from this branch, but swift version of the generated app should be inherited from the pod.

**Comment by benasher44** [comment]
The only failure left is the one that will be fixed by bumping CP's pointer to Core, so this is ready to go!
