### PR TITLE
Do not attempt compilation for pods with no sources and skipping import validation

### LINKED ISSUE #7336: Pod lib lint: xcodebuild: error: The workspace named "App" does not contain a scheme named "MyProject".
* [✅] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Run  `pod lib lint --skip-import-validation --verbose --no-clean`

## What did you expect to happen?
Lint the project successfully

## What happened instead?
There is an error at the  `Building with xcodebuild` step.

```Building with xcodebuild. 
xcodebuild clean build -workspace /var/folders/7t/pzxxc43531z94d11xvjhjw7c0000gn/T/CocoaPods-Lint-20180116-3230-hvhdp6-MyProject/App.xcworkspace -scheme MyProject -configuration Release CODE_SIGN_IDENTITY=- -sdk iphonesimulator -destination id=E466A27A-2F6B-4DB2-A1C3-645CD3E52826
Build settings from command line:
    CODE_SIGN_IDENTITY = -
    SDKROOT = iphonesimulator11.2

xcodebuild: error: The workspace named "App" does not contain a scheme named "MyProject". The "-list" option can be used to find the names of the schemes in the workspace.
   Testing with xcodebuild. 
 -> MyProject (2.3.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [iOS] xcodebuild:  xcodebuild: error: The workspace named "App" does not contain a scheme named "MyProject". The "-list" option can be used to find the names of the schemes in the workspace.
```

```xcodebuild clean build -workspace /var/folders/7t/pzxxc43531z94d11xvjhjw7c0000gn/T/CocoaPods-Lint-20180116-3230-hvhdp6-MyProject/App.xcworkspace -scheme MyProject -configuration Release CODE_SIGN_IDENTITY=- -sdk iphonesimulator -destination id=E466A27A-2F6B-4DB2-A1C3-645CD3E52826```

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
    RubyGems : 2.7.4
        Host : Mac OS X 10.13.1 (17B1003)
       Xcode : 9.2 (9C40b)
         Git : git version 2.6.2
Ruby lib dir : /Users/scottire/.rvm/rubies/ruby-2.5.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 54b623b82dcffd3d00e699c2c856d5e447f53b98
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

[Project](https://github.com/flomio/flomio_mw_releases/blob/master/FlomioSDK.podspec)

### PR DESCRIPTION
**Pull request by dnkoutso**
closes #7336 

If `--skip-import-validation` is used we never invoke the `App` scheme since it will avoid linking the pod and during this case we choose the pods scheme during validation in order to just build it.

However, if the pod has no sources then there is no scheme to invoke which is the edge case fixed here.

### CODE REVIEW

**Comment by dnkoutso** [comment]
This will go to 1.5.0 not 1.4.0 as its about to ship.

File: lib/cocoapods/validator.rb [hunk 1]
```diff
@@ -556,21 +556,26 @@ def build_pod
...
+                     pod_target.label if pod_target.should_build?
                    else
                      'App'
                    end
-          output = xcodebuild('build', scheme, 'Release')
-          UI.puts output
-          parsed_output = parse_xcodebuild_output(output)
-          translate_output_to_linter_messages(parsed_output)
+          if scheme.nil?
+            UI.warn "Skipping compilation with `xcodebuild' because target contains no sources.\n".yellow
```
Comment (paulb777) [inline lib/cocoapods/validator.rb]: Inconsistent quotes around xcodebuild

Comment (dnkoutso) [reply lib/cocoapods/validator.rb]: ah nice, a problem everywhere here, fixing.

Comment (dnkoutso) [reply lib/cocoapods/validator.rb]: fixed

**Comment by dnkoutso** [comment]
heh, requires integration specs update https://github.com/CocoaPods/cocoapods-integration-specs/pull/132

#dotherightthing

**Comment by dnkoutso** [comment]
Should go green.
