### PR TITLE
Fix `INFOPLIST_FILE` being overridden when set in `pod_target_xcconfig`

### LINKED ISSUE #7530: Question: How to set CFBundleVersion in Pod Framework?
I apologize for the clutter, but I've googled around for an answer to this and haven't found an answer. I'm developing an SDK in a Pod as a framework that wraps a REST api. I don't care what the users of this pod set their `CFBundleVersion` value to. That number has no meaning to our system. Instead, I need to declare the `CFBundleVersion` for each release of the pod so that we can know what versions are out in the wild. And it seems like bad form to require each user of the framework to put the correct `post_install` script in their Podfile.

I'm sure there must be a way to do this and that I just haven't found the right documentation. Can someone enlighten me.

🌈

### PR DESCRIPTION
**Pull request by amorde**
Fixes #7530

@dnkoutso We may also be able to mark #3032 and #7486 as done, unless they should stay open for future DSL to be added

Podspecs utilizing this may need to set `s.resources = 'PATH_TO_INFO_PLIST.plist'` so that the file is not discarded during install

### CODE REVIEW

**Comment by amorde** [comment]
After a second look I don't think this fixes #7486

File: lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb [hunk 1]
```diff
@@ -170,6 +170,7 @@ def create_info_plist_file(path, native_target, version, platform, bundle_packag
               add_file_to_support_group(path) if add_to_support_group
 
               native_target.build_configurations.each do |c|
+                next unless c.resolve_build_setting('INFOPLIST_FILE').nil?
```
Comment (dnkoutso) [inline lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb]: this might not be the right spot to debounce it. This means the file was actually written to disk but not "linked" to the project.

Could we check on this a bit earlier within `pod_target_installer` instead?

**Comment by dnkoutso** [comment]
Yeah I am not sure about #3032 and #7486. We can probably comment and announce this is a relatively easily work around but there might still be a case to include it in the CocoaPods library.

**Comment by amorde** [comment]
Will squash once green

File: spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb [hunk 2]
```diff
@@ -757,6 +767,34 @@ class PodsProjectGenerator
...
+              @pod_target.stubs(:requires_frameworks?).returns(true)
+              @installer.install!
+              group = @project['Pods/BananaLib/Support Files']
+              group.children.map(&:display_name).sort.should == [
+                'BananaLib-Info.plist',
+                'BananaLib-dummy.m',
+                'BananaLib-prefix.pch',
+                'BananaLib.modulemap',
+                'BananaLib.xcconfig',
+              ]
```
Comment (amorde) [inline spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb]: I couldn't find an existing unit test that covered this - if there is one I'll remove this

File: lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb [hunk 3]
```diff
@@ -114,6 +114,18 @@ def skip_pch?(specs)
...
 
+          # True if info.plist generation should be skipped
+          #
+          # @param [PXNativeTarget] native_target
+          #
+          # @return [Boolean] Whether the target should build an Info.plist file
+          #
+          def skip_info_plist?(native_target)
+            return true if target.static_framework?
+            existing_setting = native_target.resolved_build_setting('INFOPLIST_FILE', true).values.compact
```
Comment (dnkoutso) [inline lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb]: I guess passing `true` here makes sense since we know the `.xcconfig` has been created and assigned there and its within our control.
