### PR TITLE
Fix static binaries check

### LINKED ISSUE #3194: 0.36 RC1 is too restrictive about transitively included static libs
Using Swift pods requires `use_frameworks!`, which is fine. But doing that means including pods that have dependencies that include static libs (ARAnalytics is a good example) breaks everything:

```
[!] The 'Pods' target has transitive dependencies that include static binaries: (/Users/ash/bin/eidolon/Pods/HockeySDK/Vendor/CrashReporter.framework and /Users/ash/bin/eidolon/Pods/Mixpanel/Mixpanel/libMPCategoryHelpers.a)
```

The error message could be more clear that this is broke and not just a warning. 

I'll include an example shortly.

### PR DESCRIPTION
**Pull request by neonichu**
This limits our check for static transitive dependencies to those which are known to not work.

Reasoning:
- `should_build? == false` means the static library or framework will be linked directly to the user target
- Linking a pod target which depends transitively on the same static library or framework will fail because of missing symbols
- Linking both targets against the static library or framework will likely result in duplicated symbols

=> this kind of dependency cannot be fulfilled if the integration is done via frameworks.

This fixes #3194

### CODE REVIEW

File: spec/unit/installer_spec.rb [hunk 1]
```diff
@@ -184,12 +184,21 @@ def @installer.write_pod_project
...
 
-        @installer = Installer.new(config.sandbox, podfile, lockfile)
+      it 'detects transitive static dependencies which are linked directly to the user target' do
+        Sandbox::FileAccessor.any_instance.stubs(:vendored_libraries).returns([Pathname('libThing.a')])
+        @installer = Installer.new(config.sandbox, @podfile, @lockfile)
         should.raise(Informative) { @installer.install! }.message.should.match /transitive.*libThing/
       end
+
+      it 'allows transitive static dependencies which contain other source code' do
+        Sandbox::FileAccessor.any_instance.stubs(:source_files).returns([Pathname('/yolo.m')])
```
Comment (segiddins) [inline spec/unit/installer_spec.rb]: please be consistent with absolute/relative paths, even in the specs

**Comment by segiddins** [comment]
:+1:

File: spec/unit/installer_spec.rb (hunk 1 above)
Comment (neonichu) [inline spec/unit/installer_spec.rb]: Because the `install!` is actually running further in this spec, it needs to be absolute to not fail. Let's change the other spec to also be absolute?

Comment (segiddins) [inline spec/unit/installer_spec.rb]: sure, just so long as they're consistent.
