### PR TITLE
Fix crash when targets missing in Podfile

### LINKED ISSUE #9745: undefined method `empty?' for nil:NilClass at target_validator.rb:118 when changing swift_versions in pre_install step
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Got the following `Podfile`:

```ruby
use_frameworks!
platform :ios, '11.0'

pod 'InputMask', '4.2.0'

pre_install do |installer|
  installer.analysis_result.specifications.each do |s|
    s.swift_versions << '4.2' if s.swift_versions.empty?
  end
end
```

## What did you expect to happen?

`pod install` does not crash

## What happened instead?

`pod install` crashed with:

```
NoMethodError - undefined method `empty?' for nil:NilClass
/Users/user/Desktop/vendor/bundle/ruby/2.6.0/bundler/gems/Cocoapods-2b774aa58f1e/lib/cocoapods/installer/xcode/target_validator.rb:118:in `block in verify_swift_pods_swift_version'
```

## CocoaPods Environment

Tested with cocoapods versions:
- `1.8.4`: not crashing
- `1.9.1`: crashing
- latest on master at the time of writing: crashing

Catalina 10.15.4, Xcode 11.3.1.

## Project that demonstrates the issue

Just run `pod install` in the `Podfile` I shown above.

Looks similar issue than the one explained in https://github.com/CocoaPods/CocoaPods/pull/9688

### PR DESCRIPTION
**Pull request by paulb777**
Fix #9745

### CODE REVIEW

File: spec/unit/installer/xcode/target_validator_spec.rb [hunk 1]
```diff
@@ -435,6 +435,24 @@ def create_validator(sandbox, podfile, lockfile)
...
+          it 'does not crash if targets are missing' do
+            fixture_path = ROOT + 'spec/fixtures'
+            config.repos_dir = fixture_path + 'spec-repos'
+            podfile = Podfile.new do
+              project(fixture_path + 'SampleProject/SampleProject').to_s
+              platform :ios, '10.0'
+              install! 'cocoapods', :integrate_targets => false
+              pod 'MultiSwift', :path => (fixture_path + 'multi-swift').to_s
+              supports_swift_versions '< 3.0'
+              target 'SampleProject'
```
Comment (dnkoutso) [inline spec/unit/installer/xcode/target_validator_spec.rb:447]: This seems to have a target?

Comment (paulb777) [reply spec/unit/installer/xcode/target_validator_spec.rb]: Fixed, Unlike the real code, the create_validator method didn't create pod targets for the validator when there were no targets in the Podfile.
