### PR TITLE
Remove duplicate framework names

### LINKED ISSUE #6711: Code sharing with extension using the subspec approach doesn't work
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈

# Report

## What did you do?

* Setup the project as described in [#5373](https://github.com/CocoaPods/CocoaPods/issues/5373) ([comment](https://github.com/CocoaPods/CocoaPods/issues/5373#issuecomment-220486539), sharing a subset of functionality with an extension). Initially reported this in that thread, but felt like it should have it's own issue.
* Run `pod install`

### Details:
A private framework with two subspecs:
- `App`: for the main app target
- `Extension`: for the extension target, uses some files "from" the `App` subspec

### `podspec`:

```ruby
Pod::Spec.new do |s|
  s.name        = 'MyFramework'
  s.version       = '0.1.0'
  s.summary       = 'Dummy Framework'
  s.homepage      = 'https://github.com/zierka'
  s.license       = 'MIT'
  s.author        = {'Zier Erik' => 'erik.interwebz@gmail.com'}

  s.source        = {:git => 'git@github.com:zierka/subspec-error-example.git', :tag => s.version.to_s}

  s.requires_arc  = true
  s.platform      = :ios
  s.ios.deployment_target = '10.0'

  s.default_subspecs = 'App'

  s.subspec 'App' do |app|
    app.source_files = [
      'App/**/*.{swift}'
    ]
  end

  s.subspec 'Extension' do |ext|
    ext.source_files = [
      'App/CoreClass.swift',
      'Extension/**/*.{swift}'
    ]

    ext.exclude_files = [
      'App/AppClass.swift'
    ]
  end

end
```

### A simple xcode project, with 2 targets:
- the main app target has the `MyFramework` as dependency in the Podfile
- the extension target has the `MyFramework/Extension` as dependency

### `Podfile`:

```ruby
platform :ios, '10.0'
use_frameworks!

target 'SubspecProblemExample' do
  pod 'MyFramework', :path => "../MyFramework" . # equal to MyFramework/App as that's declared for default_subspecs
end

target 'todayWidget' do
  pod 'MyFramework/Extension', :path => "../MyFramework"
end
```

## What did you expect to happen?

Successful integration, creating a workspace. 

## What happened instead?

`[!] The 'Pods-SubspecProblemExample' target has frameworks with conflicting names: myframework.`

I'm aware that this error is mentioned in a quite a few issues, I read through all of them, but it's still not clear to me what the real problem is. 

* Is the described subspec approach not supported anymore?
I never got a confirmation about this, and based on the replies in that thread, it's described as a working solution, hence my confusion.
* If it's not working anymore, is there any other way to share code like this? Note that one of the key reasons for sharing code this way is to exclude usage of unavailable code from the extension (e.g. `UIApplication`), but still able to use it in the main target.

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.2 (8E2002)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : 
[REDACTED: removed some private spec repositories]
               master - https://github.com/CocoaPods/Specs.git @ 73b41a4e0658de58a2031c6e2da00f37ae5813f3
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
https://github.com/zierka/subspec-error-example

### PR DESCRIPTION
**Pull request by abiligiri**
closes #6711

A Pod target could require multiple subspecs, but the product_module_name can
be specified only at the root spec.

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Remove duplicate framework names  
  [abiligiri](https://github.com/abiligiri)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by dnkoutso** [comment]
Needs a test and changelog entry, and me to think about this a bit more.

File: spec/unit/installer/xcode/target_validator_spec.rb [hunk 1]
```diff
@@ -92,6 +92,32 @@ def create_validator(sandbox, podfile, lockfile)
             @validator = create_validator(config.sandbox, podfile, lockfile)
             should.not.raise(Informative) { @validator.validate! }
           end
+
+          it 'allows multiple subspecs' do
```
Comment (dnkoutso) [inline spec/unit/installer/xcode/target_validator_spec.rb]: can you please provide a more describe test name?

**Comment by abiligiri** [comment]
I am working on the CHANGELOG entry. Somehow editing in TextMate is changing characters all over the file

File: CHANGELOG.md [hunk 2]
```diff
@@ -38,6 +38,9 @@ To install release candidates run `[sudo] gem install cocoapods --pre`
 * Provide a better error message when references are missing for non-source files
   [David Airapetyan](https://github.com/davidair)
   [#4887](https://github.com/CocoaPods/CocoaPods/issues/4887)
+* Remove duplicate framework names
```
Comment (dnkoutso) [inline CHANGELOG.md]: needs extra line above.

**Comment by dnkoutso** [comment]
This LGTM.

**Comment by dnkoutso** [comment]
@abiligiri I checked out your fork and branch. I removed your `.uniq` change but the test still passes...something is wrong in your tests case or the change does not work properly.

Please investigate otherwise we cannot merge this.

**Comment by dnkoutso** [comment]
screen_shot_2017-07-17_at_10_14_58_am

**Comment by abiligiri** [comment]
@dnkoutso thanks for checking. Can you let me know how I will be able to run the test locally ? Specifically any documentation to pointing to the version of ruby required. I am fairly new to Ruby and I tried the Cocoapods/Rainforest guide to setup the development environment. I was not successful.

**Comment by dnkoutso** [comment]
Just use `be bacon "./spec/unit/installer/xcode/target_validator_spec.rb"`

**Comment by dnkoutso** [comment]
You may need to do `git submodule update --init --recursive` first though as the test will clone the master specs repo.

**Comment by dnkoutso** [comment]
@abiligiri did you revert your change? There is no actual code changes here?

**Comment by abiligiri** [comment]
@dnkoutso I am trying to get the exact test case required to reproduce the problem. I am able to run the tests locally now. I will update this PR soon once I have a test and the fix.

**Comment by dnkoutso** [comment]
👍

**Comment by abiligiri** [comment]
@dnkoutso Is it possible for the pod_targets generated at unit test time to be different than those generated when actually using the pod tool? I do see the installation_option set to
```
options.integrate_targets = false
```
in target_validator_spec.rb

**Comment by dnkoutso** [comment]
@abiligiri absolutely. Check out some other specs around the same file. You can easily stub out and return a different set of pod targets.

File: spec/unit/installer/xcode/target_validator_spec.rb [hunk 3]
```diff
@@ -34,7 +34,30 @@ def create_validator(sandbox, podfile, lockfile)
           TargetValidator.new(aggregate_targets, pod_targets)
         end
 
+        # @return [AnalysisResult]
+        #
+        def create_validator_with_integrate_target(sandbox, podfile, lockfile)
```
Comment (dnkoutso) [inline spec/unit/installer/xcode/target_validator_spec.rb]: maybe refactor the method above to pass a bool param?

**Comment by dnkoutso** [comment]
👍 

@DanToml if you'd like to take a look as well. Does not need to part of 1.3.0.rc.1

**Comment by dnkoutso** [comment]
@abiligiri one last request, can you squash to a single commit?

File: CHANGELOG.md [hunk 4]
```diff
@@ -39,6 +39,10 @@ To install release candidates run `[sudo] gem install cocoapods --pre`
   [David Airapetyan](https://github.com/davidair)
   [#4887](https://github.com/CocoaPods/CocoaPods/issues/4887)
 
+* Remove duplicate framework names
```
Comment (dnkoutso) [inline CHANGELOG.md]: @abiligiri can this changelog entry be a bit more descriptive? Its just too generic, thankfully there is the link to the GH issue but still...

**Comment by abiligiri** [comment]
@dnkoutso and @DanToml 

Will this be merged soon?

**Comment by keith** [comment]
I found an issue with this change, it seems to have broken validation when you actually have duplicate dependencies https://github.com/CocoaPods/CocoaPods/issues/7525
