### PR TITLE
Warn instead of throwing an exception when dev pod's license file is missing

### LINKED ISSUE #7377: Error while installing pods
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?
I added a new developer in my bitbucket account under specific repo,
when he cloned the repo, run pod install, it generated the error below.

* What did you expect to happen?
at least all pods will be installed without error

* What happened instead?
Error below

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.2 (17C205)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6218c16db238fa19c829798183dd605f05a60fe4
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project

platform :ios, '8.0'
use_frameworks!

def shared_pods
    # 87.27
    pod 'AFNetworking', '~> 2.5.0'
    
    # working
    pod 'SDWebImage'
    
    # pod 'SWTableViewCell'
    pod 'FastImageCache'
    
    # unused
    # pod 'ABPadLockScreen', '~> 3.3.0'
    
    pod 'EDStarRating'
    
    pod 'KeychainAccess', '~> 2.4.0'
    pod 'SWXMLHash', '~> 2.1.0'
    pod 'SSZipArchive'
    
    # custom
    pod 'MBProgressHUD-Imonggo', { git: 'https://github.com/allanmacatingrao/MBProgressHUD-Imonggo.git' }
    pod 'NYAlertViewController-Imonggo', { git: 'https://github.com/allanmacatingrao/NYAlertViewController-Imonggo.git' }
    pod 'KAProgressLabel-Imonggo', { git: 'https://github.com/allanmacatingrao/KAProgressLabel-Imonggo.git' }
    pod 'NumPad-Imonggo', { git: 'https://github.com/allanmacatingrao/NumPad-Imonggo.git' }
    
    pod 'sReto', '~> 1.4.1'
    
    
    
    # image upload
    # pod 'TGCameraViewController' <<< Not working
    
    pod 'TGCameraViewController', :path => './'
    pod 'TOCropViewController', '~>2.0.11'
end

target 'Imonggo_Store' do

   # 87.27
   pod 'AFNetworking', '~> 2.5.0'
	
	# working
	pod 'SDWebImage'
	
	# pod 'SWTableViewCell'
	pod 'FastImageCache'
	
	# unused
    # pod 'ABPadLockScreen', '~> 3.3.0'
	
	pod 'EDStarRating'
	
	pod 'KeychainAccess', '~> 2.4.0'
	pod 'SWXMLHash', '~> 2.1.0'
	pod 'SSZipArchive'
	
	# custom
	pod 'MBProgressHUD-Imonggo', { git: 'https://github.com/allanmacatingrao/MBProgressHUD-Imonggo.git' }
	pod 'NYAlertViewController-Imonggo', { git: 'https://github.com/allanmacatingrao/NYAlertViewController-Imonggo.git' }
	pod 'KAProgressLabel-Imonggo', { git: 'https://github.com/allanmacatingrao/KAProgressLabel-Imonggo.git' }
	pod 'NumPad-Imonggo', { git: 'https://github.com/allanmacatingrao/NumPad-Imonggo.git' }
	
	pod 'sReto', '~> 1.4.1'
	
	
	# image upload
	# pod 'TGCameraViewController' <<< Not working
	
	pod 'TGCameraViewController', :path => './'
	pod 'TOCropViewController', '~>2.0.11'
    shared_pods
	
	
	pod 'Fabric'
	pod 'Crashlytics'
end

#target 'ImonggoJFCUITests' do
#	pod 'KIF', '~> 3.2.0'
#end
#target 'Imonggo iPad JFCTests' do
#	pod 'KIF', '~> 3.2.0'
#end
```

### Error

```
Errno::ENOENT - No such file or directory @ realpath_rec - /Users/eleazertoluan/Documents/imonggo-enterprise-jfc/LICENSE
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/project.rb:190:in `realpath'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/project.rb:190:in `realpath'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/project.rb:190:in `add_file_reference'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:122:in `block (3 levels) in add_developer_files'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:120:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:120:in `block (2 levels) in add_developer_files'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:115:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:115:in `block in add_developer_files'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:114:in `add_developer_files'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:43:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:163:in `install_file_references'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:184:in `block in generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:183:in `generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:119:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

### PR DESCRIPTION
**Pull request by amorde**
Closes #7377 

@dnkoutso I double checked the other files and it seems the license file is the only one with the problem, due to the way it checks the Podspec and falls back to a glob pattern

### CODE REVIEW

**Comment by dnkoutso** [comment]
@amorde 👍 needs `bundle exec rubocop -a`

File: lib/cocoapods/sandbox/file_accessor.rb [hunk 1]
```diff
@@ -310,13 +310,24 @@ def docs
...
+          if File.exists?(license_path)
+            spec_license = license_path
+          else
+            UI.warn "A license was specified in podspec `#{spec.name}` but the file does not exist - #{license_path}"
+          end
+        end
+
         if podspecs.size <= 1
-          result += [license, readme, podspecs, docs]
+          license_found = license
```
Comment (dnkoutso) [inline lib/cocoapods/sandbox/file_accessor.rb]: any reason for this extra reference here?

Comment (amorde) [reply lib/cocoapods/sandbox/file_accessor.rb]: In this case, I want the spec license *or* the auto detected glob, but the pathname returned here might not exist if the Podspec specifies a path that doesn't exist. Couldn't think of a better way to keep that logic and also have the warning printed above

Comment (amorde) [reply lib/cocoapods/sandbox/file_accessor.rb]: @dnkoutso  Reworked this a bit, let me know what you think

**Comment by amorde** [comment]
Pulled out the logic for checking the spec's `license[:file]` attribute into its own method

File: lib/cocoapods/sandbox/file_accessor.rb [hunk 2]
```diff
@@ -305,17 +305,36 @@ def docs
         path_list.glob([GLOB_PATTERNS[:docs]])
       end
 
+      # Validates that the podspec's `license` file exists if a path is specified
+      # Returns the pathname if found and the path exists
+      #
+      # @return [Pathname] the path of the license file, if specified and valid
+      #
+      def validate_spec_license!
```
Comment (dnkoutso) [inline lib/cocoapods/sandbox/file_accessor.rb]: Any reason this method name includes `!`? I am not a ruby expert, but I am under the impression that using `!` means that the method will alter state of an object. Perhaps maybe because it might also crash? 

Neither of the above appear to be true I think here (besides the warning).

Also I think the word `validate` is a bit misleading here as this method should probably be `void` versus this one actually returning a `Pathname` here.

Are both of these questions a pattern in this file?

Comment (amorde) [reply lib/cocoapods/sandbox/file_accessor.rb]: Ah, sorry that's my lack of experience in ruby showing. My main concern here was that I wanted a method which would return the Pathname if it exists and is valid, but also will print a warning if the path is missing. I can move this logic back to inside `developer_files` if that is preferred

**Comment by amorde** [comment]
Trying to investigate the integration test failures

**Comment by amorde** [comment]
Tests passing - let me know if you have additional comments. I reworked it a bit in response to your review

File: lib/cocoapods/sandbox/file_accessor.rb [hunk 3]
```diff
@@ -305,17 +301,31 @@ def docs
...
+          absolute_path if File.exist?(absolute_path)
+        end
+      end
+
       # @return [Array<Pathname>] Paths to include for local pods to assist in development
       #
       def developer_files
         podspecs = specs
         result = [module_map, prefix_header]
+        validate_spec_license
```
Comment (dnkoutso) [inline lib/cocoapods/sandbox/file_accessor.rb]: nit could also inline this method as there is no other callers for it

Comment (amorde) [reply lib/cocoapods/sandbox/file_accessor.rb]: Good point - will inline it

**Comment by dnkoutso** [comment]
@amorde just to be certain did you get a chance to verify with the pod in the issue?

**Comment by amorde** [comment]
@dnkoutso I wasn't able to verify it because it appears the pod that caused it is `imonggo-enterprise-jfc` which I don't have access to
